import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const COOKIE="sb_fasecolda_search_evidence_session";
const BASE="/functions/v1/superbid-fasecolda-search-evidence-dashboard";
const SEARCH="/functions/v1/superbid-fasecolda-search-dashboard";
const BATCH_REFRESH_LIMIT=6;
const GUARDRAIL="FASECOLDA_SEARCH_EVIDENCE_NOT_OVERRIDE_MATCH_OR_VALUATION";

const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]||m));
const dt=(v:unknown)=>v?new Intl.DateTimeFormat("es-CO",{timeZone:"America/Bogota",dateStyle:"short",timeStyle:"short"}).format(new Date(String(v))):"—";
const css=`:root{--bg:#f4f6f3;--p:#fff;--t:#182018;--m:#687168;--l:#dfe5de;--g:#123d2a;--g2:#1f6a49;--a:#765400;--r:#842828;--b:#425c70}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--t);font:14px/1.45 Inter,system-ui,sans-serif}a{text-decoration:none;color:inherit}.top{background:var(--g);color:#fff;padding:18px 26px;display:flex;justify-content:space-between;gap:14px;align-items:center}.top h1{margin:2px 0}.ey{font-size:10px;letter-spacing:1.4px;font-weight:800;opacity:.72}main{padding:20px 26px 45px;max-width:1720px;margin:auto}.nav,.filters,.actions,.badges{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.btn,button,select{border:1px solid var(--l);border-radius:8px;padding:8px 10px;background:#fff;font:inherit;font-weight:750}.btn,button{cursor:pointer}.primary{background:var(--g2)!important;border-color:var(--g2)!important;color:#fff!important}.notice{padding:12px 14px;border:1px solid #ead99c;background:#fff3cf;color:#65490d;border-radius:10px;margin-bottom:14px}.notice.ok{background:#e1f2e6;border-color:#b8dbc3;color:#175935}.notice.bad{background:#f4e5e5;border-color:#dfbbbb;color:var(--r)}.panel,.lot,.metric{background:var(--p);border:1px solid var(--l);border-radius:13px}.panel{margin-bottom:14px}.head{padding:15px 17px;border-bottom:1px solid var(--l);display:flex;justify-content:space-between;gap:10px;align-items:center}.head h2,.lot h2{margin:0}.sub{display:block;color:var(--m);font-size:11px}.stack{display:grid;gap:12px}.lot{padding:16px}.meta{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:12px 0}.kv,.metric{background:#f8faf7;padding:10px;border-radius:8px}.kv span,.metric span{display:block;color:var(--m);font-size:10px;text-transform:uppercase}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin-bottom:14px}.metric strong{font-size:20px}.pill{font-size:10px;font-weight:800;border-radius:99px;padding:5px 8px;display:inline-block}.ready{background:#daf0e1;color:#175935}.refresh,.nocodes{background:#fff0c9;color:var(--a)}.identity,.missing{background:#f4dfdf;color:#7f2424}.year,.detail{background:#e8eef3;color:#425c70}.neutral{background:#ecefec;color:#586158}.codes{display:flex;gap:5px;flex-wrap:wrap;margin:9px 0}.code{font-family:ui-monospace,monospace;background:#eef1ed;border-radius:6px;padding:5px 7px}.login{width:min(430px,92vw);margin:15vh auto;background:#fff;border:1px solid var(--l);border-radius:16px;padding:28px}.login input{width:100%;border:1px solid var(--l);border-radius:8px;padding:9px}.login button{width:100%;margin-top:10px}.err{color:var(--r);font-weight:700}@media(max-width:1050px){.metrics,.meta{grid-template-columns:repeat(2,1fr)}main{padding:13px}.top{align-items:flex-start}}`;

function html(title:string,body:string,status=200,headers:Record<string,string>={}){return new Response(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${css}</style></head><body>${body}</body></html>`,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store",...headers}})}
async function db(path:string,init:RequestInit={}){return fetch(`${U}${path}`,{...init,headers:{apikey:K,authorization:`Bearer ${K}`,"content-type":"application/json",...(init.headers||{})}})}
async function rows(path:string){const r=await db(path);if(!r.ok)throw new Error(`GET ${r.status}: ${(await r.text()).slice(0,220)}`);return r.json()}
async function one(path:string){const xs=await rows(path);return xs[0]||null}
function cookie(req:Request){for(const p of(req.headers.get("cookie")||"").split(";")){const[k,...v]=p.trim().split("=");if(k===COOKIE)return decodeURIComponent(v.join("="))}return""}
async function valid(t:string){if(!t||t.length<32||t.length>256)return false;const r=await db("/rest/v1/rpc/dashboard_token_valid",{method:"POST",body:JSON.stringify({p_token:t})});return r.ok&&(await r.json())===true}
function safeLot(v:unknown){const x=String(v||"").trim();return /^\d{5,12}$/.test(x)?x:""}
function pathOf(req:Request){const p=new URL(req.url).pathname,i=p.indexOf("/superbid-fasecolda-search-evidence-dashboard");return i>=0?(p.slice(i+"/superbid-fasecolda-search-evidence-dashboard".length)||"/"):p}
function lotFromPath(p:string){const m=p.match(/^\/lots\/(\d{5,12})(?:\/|$)/);return m?safeLot(m[1]):""}
function redirect(location:string,headers:Record<string,string>={}){return new Response(null,{status:303,headers:{location,"cache-control":"no-store",...headers}})}
function login(error=false,lot=""){return html("SUPERBID — Search Evidence",`<form class="login" method="post" action="${BASE}/login">${lot?`<input type="hidden" name="lot" value="${esc(lot)}">`:""}<div class="ey">SUPERBID · v0.60</div><h1>Fasecolda Search Evidence</h1><p class="sub">Acceso privado. Esta capa observa y reutiliza evidencia pública de búsqueda; no confirma términos, no ejecuta el matcher y no crea una valoración.</p>${lot?`<p class="sub">Continuar con lote ${esc(lot)} después de autenticar.</p>`:""}${error?'<p class="err">Credencial inválida.</p>':""}<input type="password" name="password" autocomplete="current-password" required placeholder="Clave de acceso"><button class="primary">Entrar</button></form>`,error?401:200)}
const nav=`<nav class="nav"><a class="btn" href="/functions/v1/superbid-dashboard">Dashboard</a><a class="btn" href="/functions/v1/superbid-readiness-dashboard">Readiness</a><a class="btn" href="/functions/v1/superbid-fasecolda-workbench">Workbench</a><a class="btn" href="${SEARCH}">Search humano</a><form method="post" action="${BASE}/logout"><button>Salir</button></form></nav>`;

const SELECT="external_lot_id,lot_id,title,brand,line,model_year,city,seller,current_bid_cop,closes_at,hours_to_close,effective_status,candidate_count,current_search_term,suggested_search_term,normalized_suggested_term,diagnostic_reason,input_disposition,evidence_search_http_status,evidence_code_count,evidence_codes,evidence_detail_http_status,evidence_observed_for_external_lot_id,evidence_fingerprint,evidence_observed_at,evidence_fresh,year_compatible_code_count,evidence_state,operator_next_action,suggested_term_reviewable,evidence_age_hours,evidence_state_rank,evidence_interpretation";
const REFRESH_STATES=new Set(["SUGGESTED_EVIDENCE_MISSING","SUGGESTED_EVIDENCE_STALE","SUGGESTED_DETAIL_UNAVAILABLE"]);
function statePill(v:string){const c=v==="SUGGESTED_YEAR_COMPATIBLE_CODES"?"ready":REFRESH_STATES.has(v)?"refresh":v==="SUGGESTED_NO_CODES"?"nocodes":v==="IDENTITY_INPUT_REVIEW"?"identity":v==="MISSING_YEAR"?"missing":v==="SUGGESTED_NO_YEAR_COMPATIBLE_CODES"?"year":"detail";return `<span class="pill ${c}">${esc(v)}</span>`}
function humanUrl(x:any){const id=encodeURIComponent(String(x.external_lot_id||""));return `${SEARCH}?lot=${id}&reason=${encodeURIComponent(x.diagnostic_reason||"ALL")}`}
async function loadQueueCase(lot:string){return one(`/rest/v1/dashboard_fasecolda_search_evidence_queue_v60?select=${encodeURIComponent(SELECT)}&external_lot_id=eq.${encodeURIComponent(lot)}&limit=1`)}
async function refreshRpc(lot:string,term:string){const r=await db("/rest/v1/rpc/dashboard_refresh_fasecolda_search_term_evidence_v60",{method:"POST",body:JSON.stringify({p_external_lot_id:lot,p_term:term})});if(!r.ok)throw new Error((await r.text()).slice(0,350));return r.json()}

async function board(req:Request){
  const u=new URL(req.url),lot=safeLot(u.searchParams.get("lot")),state=(u.searchParams.get("state")||"ALL").toUpperCase();
  let q=`/rest/v1/dashboard_fasecolda_search_evidence_queue_v60?select=${encodeURIComponent(SELECT)}&order=evidence_state_rank.asc,closes_at.asc.nullslast,external_lot_id.asc&limit=200`;
  if(lot)q+=`&external_lot_id=eq.${encodeURIComponent(lot)}`;
  const all=await rows(q);
  const states=new Set(all.map((x:any)=>String(x.evidence_state||"")));
  const xs=state==="ALL"||!states.has(state)?all:all.filter((x:any)=>String(x.evidence_state||"")===state);
  const counts={total:all.length,reviewable:all.filter((x:any)=>x.suggested_term_reviewable===true).length,refresh:all.filter((x:any)=>REFRESH_STATES.has(String(x.evidence_state||""))).length,nocodes:all.filter((x:any)=>x.evidence_state==="SUGGESTED_NO_CODES").length,noyear:all.filter((x:any)=>x.evidence_state==="SUGGESTED_NO_YEAR_COMPATIBLE_CODES").length,blocked:all.filter((x:any)=>x.input_disposition!=="EXPLORABLE").length};
  const metrics=[["Casos Search",counts.total],["Sugerido revisable",counts.reviewable],["Evidencia por refrescar",counts.refresh],["Sugerido sin códigos",counts.nocodes],["Sin códigos para año",counts.noyear],["Entrada bloqueada",counts.blocked]].map(([k,v])=>`<div class="metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join("");
  const opts=["ALL",...Array.from(states).sort()].map(v=>`<option value="${esc(v)}" ${v===state?"selected":""}>${esc(v)}</option>`).join("");
  const filter=`<form class="filters" method="get">${lot?`<input type="hidden" name="lot" value="${esc(lot)}">`:""}<select name="state">${opts}</select><button>Filtrar</button>${lot?`<a class="btn" href="${BASE}">Salir de modo lote</a>`:""}</form>`;
  const batch=counts.refresh>0&&!lot?`<form method="post" action="${BASE}/refresh-next"><button class="primary">Refrescar próximos ${Math.min(BATCH_REFRESH_LIMIT,counts.refresh)} términos únicos</button><span class="sub">POST explícito · máximo ${BATCH_REFRESH_LIMIT} términos · secuencial · sin match/override.</span></form>`:"";
  const cards=xs.map((x:any)=>{const codes=Array.isArray(x.evidence_codes)?x.evidence_codes.slice(0,10).map((c:unknown)=>`<span class="code">${esc(typeof c==="string"?c:JSON.stringify(c))}</span>`).join(""):"";const refresh=x.input_disposition==="EXPLORABLE"&&REFRESH_STATES.has(String(x.evidence_state||""))?`<form method="post" action="${BASE}/lots/${esc(x.external_lot_id)}/refresh"><button class="primary">Refrescar evidencia del sugerido</button></form>`:"";const inputBlock=x.input_disposition!=="EXPLORABLE"?`<div class="notice bad"><strong>${esc(x.input_disposition)}.</strong> No se consulta Fasecolda hasta corregir la identidad/año canónico de entrada.</div>`:"";return `<article class="lot"><div class="head" style="padding:0 0 10px;border:0"><div><h2>${esc(x.title)}</h2><div class="sub">Lote ${esc(x.external_lot_id)} · ${esc([x.city,x.seller].filter(Boolean).join(" · "))}</div></div><div class="badges">${statePill(String(x.evidence_state||""))}<span class="pill neutral">${esc(x.operator_next_action||"—")}</span></div></div><div class="meta"><div class="kv"><span>Marca</span><strong>${esc(x.brand||"—")}</strong></div><div class="kv"><span>Año</span><strong>${esc(x.model_year??"—")}</strong></div><div class="kv"><span>Término actual</span><strong>${esc(x.current_search_term||"—")}</strong></div><div class="kv"><span>Sugerido</span><strong>${esc(x.suggested_search_term||"—")}</strong></div><div class="kv"><span>Códigos búsqueda</span><strong>${esc(x.evidence_code_count??"—")}</strong></div><div class="kv"><span>Compatibles año</span><strong>${esc(x.year_compatible_code_count??0)}</strong></div></div>${inputBlock}<div class="codes">${codes||'<span class="sub">Sin códigos cacheados.</span>'}</div><div class="sub">Observado: ${dt(x.evidence_observed_at)} · HTTP búsqueda ${esc(x.evidence_search_http_status??"—")} · HTTP detalle ${esc(x.evidence_detail_http_status??"—")} · evidencia disparada por lote ${esc(x.evidence_observed_for_external_lot_id||"—")}</div><div class="actions" style="margin-top:12px">${refresh}<a class="btn" href="${esc(humanUrl(x))}">${x.suggested_term_reviewable?"Revisar término en Search humano":"Abrir exploración humana"}</a><a class="btn" href="/functions/v1/superbid-fasecolda-workbench?lot=${esc(x.external_lot_id)}">Workbench</a><a class="btn" href="/functions/v1/superbid-dashboard/lots/${esc(x.external_lot_id)}">Lote</a></div></article>`}).join("");
  const refreshed=u.searchParams.get("refreshed")==="1"?'<div class="notice ok">Evidencia pública actualizada. No se confirmó ningún término ni se ejecutó el matcher.</div>':"";
  return html("SUPERBID — Search Evidence",`<header class="top"><div><div class="ey">SUPERBID · v0.60</div><h1>Fasecolda Search Evidence Queue</h1></div>${nav}</header><main>${refreshed}${lot?`<div class="notice ok"><strong>Modo lote ${esc(lot)}.</strong> Contexto exacto preservado.</div>`:""}<div class="notice"><strong>${GUARDRAIL} · AUTOMATED_SEARCH_VARIANT_NOT_OVERRIDE_OR_MATCH · CASE_CONTEXT_ROUTING_NOT_BUY_SIGNAL.</strong> La presencia de códigos, incluso compatibles con el año, solo habilita revisión humana del término. No elige código, no confirma override, no ejecuta matcher, no calcula valor y no modifica decisión de compra.</div><section class="metrics">${metrics}</section><section class="panel"><div class="head"><div><h2>${esc(xs.length)} casos visibles</h2><span class="sub">Evidencia por término reutilizable entre lotes; frescura operativa 24 h.</span></div>${filter}</div><div style="padding:14px 17px">${batch}</div></section><div class="stack">${cards||'<section class="lot">Sin casos para este filtro.</section>'}</div></main>`)
}

async function refreshOne(lot:string){const x=await loadQueueCase(lot);if(!x)return html("Caso no disponible",`<main><div class="notice bad">El lote ${esc(lot)} ya no está en Search Review.</div><a class="btn" href="${BASE}">Volver</a></main>`,404);if(x.input_disposition!=="EXPLORABLE")return html("Refresh bloqueado",`<main><div class="notice bad">${esc(x.input_disposition)}: no se llamó a Fasecolda.</div><a class="btn" href="${BASE}?lot=${esc(lot)}">Volver</a></main>`,409);const term=String(x.suggested_search_term||"").trim();if(!term)return html("Refresh bloqueado",`<main><div class="notice bad">No existe término sugerido seguro.</div></main>`,409);await refreshRpc(lot,term);return redirect(`${BASE}?lot=${encodeURIComponent(lot)}&refreshed=1`)}

async function refreshNext(){const xs=await rows(`/rest/v1/dashboard_fasecolda_search_evidence_queue_v60?select=${encodeURIComponent("external_lot_id,normalized_suggested_term,suggested_search_term,input_disposition,evidence_state")}&order=evidence_state_rank.asc,external_lot_id.asc&limit=200`);const unique=new Map<string,any>();for(const x of xs){if(x.input_disposition!=="EXPLORABLE"||!REFRESH_STATES.has(String(x.evidence_state||"")))continue;const key=String(x.normalized_suggested_term||"");if(key&&!unique.has(key))unique.set(key,x);if(unique.size>=BATCH_REFRESH_LIMIT)break}const targets=Array.from(unique.values());const results:any[]=[];for(const x of targets){try{const j=await refreshRpc(String(x.external_lot_id),String(x.suggested_search_term));results.push({term:x.suggested_search_term,lot:x.external_lot_id,ok:true,codes:j.code_count,detail:j.detail_count})}catch(e){results.push({term:x.suggested_search_term,lot:x.external_lot_id,ok:false,error:e instanceof Error?e.message:String(e)})}}const cards=results.map(r=>`<article class="lot"><span class="pill ${r.ok?"ready":"identity"}">${r.ok?"OBSERVADO":"ERROR"}</span><h2>${esc(r.term)}</h2><div class="sub">Lote de provenance ${esc(r.lot)}${r.ok?` · códigos ${esc(r.codes)} · detalles ${esc(r.detail)}`:` · ${esc(r.error)}`}</div></article>`).join("");return html("SUPERBID — Batch Search Evidence",`<header class="top"><div><div class="ey">SUPERBID · v0.60</div><h1>Refresh batch acotado</h1></div>${nav}</header><main><div class="notice"><strong>${GUARDRAIL}.</strong> Se procesaron ${esc(results.length)} términos únicos, secuencialmente, con máximo ${BATCH_REFRESH_LIMIT}. No se confirmó ningún término ni se ejecutó matcher.</div><div class="stack">${cards||'<section class="lot">No había evidencia faltante/obsoleta para refrescar.</section>'}</div><p><a class="btn primary" href="${BASE}">Volver a la cola</a></p></main>`)}

Deno.serve(async(req:Request)=>{try{const p=pathOf(req),u=new URL(req.url),requestedLot=lotFromPath(p)||safeLot(u.searchParams.get("lot"));if(p==="/login"&&req.method==="POST"){const f=await req.formData(),password=String(f.get("password")||""),lot=safeLot(f.get("lot"));if(!await valid(password))return login(true,lot);return redirect(lot?`${BASE}?lot=${encodeURIComponent(lot)}`:BASE,{"set-cookie":`${COOKIE}=${encodeURIComponent(password)}; Path=${BASE}; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`})}if(!await valid(cookie(req)))return login(false,requestedLot);if(p==="/logout"&&req.method==="POST")return redirect(BASE,{"set-cookie":`${COOKIE}=; Path=${BASE}; HttpOnly; Secure; SameSite=Strict; Max-Age=0`});const lot=lotFromPath(p);if(lot&&p.endsWith("/refresh")&&req.method==="POST")return refreshOne(lot);if(p==="/refresh-next"&&req.method==="POST")return refreshNext();if((p==="/"||p==="")&&req.method==="GET")return board(req);return html("No encontrado","<main>Ruta no encontrada.</main>",404)}catch(e){return html("Error",`<main><div class="notice bad">${esc(e instanceof Error?e.message:String(e))}</div></main>`,500)}});
