import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,COOKIE="sb_fasecolda_year_session";
const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]||m));
const cop=(v:any)=>v==null?"—":new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(Number(v));
const dt=(v:any)=>v?new Intl.DateTimeFormat("es-CO",{timeZone:"America/Bogota",dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const arr=(v:any)=>Array.isArray(v)&&v.length?v.join(", "):"—";
const range=(a:any,b:any)=>a==null&&b==null?"—":a===b?cop(a):`${cop(a)} – ${cop(b)}`;
const css=`:root{--bg:#f4f6f3;--p:#fff;--t:#182018;--m:#687168;--l:#dfe5de;--g:#123d2a;--g2:#1f6a49;--a:#765400;--r:#842828}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--t);font:14px/1.45 Inter,system-ui,sans-serif}a{text-decoration:none;color:inherit}.top{background:var(--g);color:#fff;padding:18px 26px;display:flex;justify-content:space-between;gap:14px;align-items:center}.top h1{margin:2px 0}.ey{font-size:10px;letter-spacing:1.4px;font-weight:800;opacity:.7}main{padding:20px 26px 45px;max-width:1740px;margin:auto}.nav,.filters,.badges{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.btn,button,select{border:1px solid var(--l);border-radius:8px;padding:8px 10px;background:#fff;font:inherit;font-weight:700}.btn,button{cursor:pointer}.btn.primary,button.primary{background:var(--g2);border-color:var(--g2);color:#fff}.notice{padding:12px 14px;border:1px solid #ead99c;background:#fff3cf;color:#65490d;border-radius:10px;margin-bottom:14px}.panel,.metric{background:var(--p);border:1px solid var(--l);border-radius:13px}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:14px}.metric{padding:14px}.metric span,.sub{display:block;color:var(--m);font-size:11px}.metric strong{font-size:22px}.head{padding:15px 17px;border-bottom:1px solid var(--l);display:flex;justify-content:space-between;gap:10px;align-items:center}.head h2{margin:0}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1650px}th,td{padding:9px 10px;border-bottom:1px solid #edf0ec;text-align:left;vertical-align:top;white-space:nowrap}th{font-size:10px;text-transform:uppercase;color:var(--m);background:#fafbf9;position:sticky;top:0}.vehicle{white-space:normal;min-width:300px}.evidence{white-space:normal;min-width:220px}.pill{font-size:10px;font-weight:800;border-radius:99px;padding:5px 8px;display:inline-block}.brand{background:#f4e5e5;color:var(--r)}.gap{background:#fff0c9;color:var(--a)}.older{background:#e8eef3;color:#425c70}.newer{background:#daf0e1;color:#175935}.missing{background:#ecefec;color:#586158}.rank{font-size:18px;font-weight:900}.login{width:min(430px,92vw);margin:15vh auto;background:#fff;border:1px solid var(--l);border-radius:16px;padding:28px}.login input{width:100%;border:1px solid var(--l);border-radius:8px;padding:9px}.login button{width:100%;margin-top:10px}.err{color:var(--r);font-weight:700}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}main{padding:13px}.top{align-items:flex-start}}`;
function html(title:string,body:string,status=200,headers:Record<string,string>={}){return new Response(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${css}</style></head><body>${body}</body></html>`,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store",...headers}})}
async function db(path:string,init:RequestInit={}){return fetch(`${U}${path}`,{...init,headers:{apikey:K,authorization:`Bearer ${K}`,"content-type":"application/json",...(init.headers||{})}})}
function cookie(req:Request){for(const p of (req.headers.get("cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k===COOKIE)return decodeURIComponent(v.join("="))}return ""}
async function valid(t:string){if(!t||t.length<32||t.length>256)return false;const r=await db("/rest/v1/rpc/dashboard_token_valid",{method:"POST",body:JSON.stringify({p_token:t})});return r.ok&&(await r.json())===true}
function pathOf(req:Request){const p=new URL(req.url).pathname,m="/superbid-fasecolda-year-dashboard",i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||"/"):p}
function login(error=false){return html("SUPERBID — Referencias por año",`<form class="login" method="post" action="/functions/v1/superbid-fasecolda-year-dashboard/login"><div class="ey">SUPERBID</div><h1>Referencias Fasecolda por año</h1><p class="sub">Acceso privado. Los años vecinos son evidencia directa y no se convierten en valoración del año faltante.</p>${error?'<p class="err">Credencial inválida.</p>':''}<input type="password" name="password" autocomplete="current-password" required placeholder="Clave de acceso"><button class="primary">Entrar</button></form>`,error?401:200)}
const nav=`<nav class="nav"><a class="btn" href="/functions/v1/superbid-fasecolda-workbench">Workbench</a><a class="btn" href="/functions/v1/superbid-fasecolda-dashboard">Resolver candidatos</a><a class="btn" href="/functions/v1/superbid-fasecolda-search-dashboard">Términos</a><a class="btn" href="/functions/v1/superbid-readiness-dashboard">Readiness</a><form method="post" action="/functions/v1/superbid-fasecolda-year-dashboard/logout"><button>Salir</button></form></nav>`;
function option(v:string,label:string,current:string){return `<option value="${esc(v)}" ${v===current?"selected":""}>${esc(label)}</option>`}
function reasonPill(v:string){const c=v==="STORED_BRAND_DIFFERS_FROM_SEARCH_TERM"?"brand":v==="YEAR_GAP_BETWEEN_REFERENCES"?"gap":v==="ONLY_OLDER_REFERENCES"?"older":v==="ONLY_NEWER_REFERENCES"?"newer":"missing";return `<span class="pill ${c}">${esc(v)}</span>`}
async function board(req:Request){const u=new URL(req.url),reason=(u.searchParams.get("reason")||"ALL").toUpperCase(),state=(u.searchParams.get("review_state")||"ALL").toUpperCase();const reasons=new Set(["STORED_BRAND_DIFFERS_FROM_SEARCH_TERM","LINE_NOT_PRESENT_IN_IMPORTED_VALUES","SAME_YEAR_REFERENCE_EXISTS_DIAGNOSTIC_STALE","YEAR_GAP_BETWEEN_REFERENCES","ONLY_OLDER_REFERENCES","ONLY_NEWER_REFERENCES","REFERENCE_YEARS_UNAVAILABLE","ALL"]),states=new Set(["REVIEW_NOW","REVIEW_SOON","WATCH","NO_HEADROOM","BLOCKED_VALUATION","CLOSED_OR_PAST","ALL"]),rr=reasons.has(reason)?reason:"ALL",rs=states.has(state)?state:"ALL";
const cr=await db("/rest/v1/dashboard_fasecolda_year_reference_diagnostics?select=year_reference_reason,diagnostic_rank&limit=300");if(!cr.ok)return html("Error","<main>No fue posible consultar diagnósticos por año.</main>",500);const all=await cr.json();const counts:Record<string,number>={};for(const x of all)counts[x.year_reference_reason]=(counts[x.year_reference_reason]||0)+1;
const sel="external_lot_id,title,stored_brand,stored_line,term_brand,line_term,model_year,city,seller,review_state,review_score,current_search_term,reference_row_count,reference_code_count,available_years,same_year_row_count,nearest_lower_year,lower_year_distance,nearest_lower_min_value_cop,nearest_lower_max_value_cop,nearest_lower_codes,nearest_upper_year,upper_year_distance,nearest_upper_min_value_cop,nearest_upper_max_value_cop,nearest_upper_codes,evidence_imported_at,year_reference_reason,diagnostic_rank,next_action,interpretation";let q=`/rest/v1/dashboard_fasecolda_year_reference_diagnostics?select=${encodeURIComponent(sel)}&order=diagnostic_rank.asc,review_score.desc,external_lot_id.asc&limit=300`;if(rr!=="ALL")q+=`&year_reference_reason=eq.${encodeURIComponent(rr)}`;if(rs!=="ALL")q+=`&review_state=eq.${encodeURIComponent(rs)}`;const r=await db(q);if(!r.ok)return html("Error","<main>No fue posible consultar casos.</main>",500);const xs=await r.json();
const cards=[["Casos",all.length],["Entre años",counts.YEAR_GAP_BETWEEN_REFERENCES||0],["Solo anteriores",counts.ONLY_OLDER_REFERENCES||0],["Solo posteriores",counts.ONLY_NEWER_REFERENCES||0],["Línea no presente",counts.LINE_NOT_PRESENT_IN_IMPORTED_VALUES||0],["Marca a revisar",counts.STORED_BRAND_DIFFERS_FROM_SEARCH_TERM||0]].map(x=>`<div class="metric"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join("");
const filter=`<form class="filters" method="get"><select name="reason">${option("ALL","Todos los diagnósticos",rr)}${option("STORED_BRAND_DIFFERS_FROM_SEARCH_TERM","Marca a revisar",rr)}${option("YEAR_GAP_BETWEEN_REFERENCES","Entre años disponibles",rr)}${option("ONLY_OLDER_REFERENCES","Solo años anteriores",rr)}${option("ONLY_NEWER_REFERENCES","Solo años posteriores",rr)}${option("LINE_NOT_PRESENT_IN_IMPORTED_VALUES","Línea no presente",rr)}${option("SAME_YEAR_REFERENCE_EXISTS_DIAGNOSTIC_STALE","Mismo año apareció",rr)}</select><select name="review_state">${option("ALL","Todos los estados",rs)}${option("REVIEW_NOW","Revisar ahora",rs)}${option("REVIEW_SOON","Revisar pronto",rs)}${option("WATCH","Vigilar",rs)}${option("BLOCKED_VALUATION","Bloqueado valoración",rs)}</select><button class="primary">Aplicar</button></form>`;
const rows=xs.map((x:any)=>`<tr><td><span class="rank">${esc(x.diagnostic_rank)}</span></td><td>${reasonPill(x.year_reference_reason)}<div class="sub">${esc(x.next_action)}</div></td><td class="vehicle"><strong>${esc(x.title)}</strong><div class="sub">Lote ${esc(x.external_lot_id)} · ${esc([x.city,x.seller].filter(Boolean).join(" · "))}</div></td><td>${esc(x.model_year)}</td><td><strong>${esc(x.stored_brand||"—")}</strong><div class="sub">término: ${esc(x.term_brand||"—")}</div></td><td>${esc(x.line_term||"—")}</td><td class="evidence">${esc(arr(x.available_years))}<div class="sub">${esc(x.reference_code_count)} códigos · fuente ${dt(x.evidence_imported_at)}</div></td><td class="evidence"><strong>${esc(x.nearest_lower_year??"—")}</strong>${x.lower_year_distance!=null?` <span class="sub">-${esc(x.lower_year_distance)} año(s)</span>`:""}<div>${range(x.nearest_lower_min_value_cop,x.nearest_lower_max_value_cop)}</div><div class="sub">códigos: ${esc(arr(x.nearest_lower_codes))}</div></td><td class="evidence"><strong>${esc(x.nearest_upper_year??"—")}</strong>${x.upper_year_distance!=null?` <span class="sub">+${esc(x.upper_year_distance)} año(s)</span>`:""}<div>${range(x.nearest_upper_min_value_cop,x.nearest_upper_max_value_cop)}</div><div class="sub">códigos: ${esc(arr(x.nearest_upper_codes))}</div></td><td>${esc(x.review_state)}</td><td><a class="btn" href="/functions/v1/superbid-dashboard/lots/${esc(x.external_lot_id)}">Lote</a> <a class="btn" href="/functions/v1/superbid-fasecolda-search-dashboard?reason=NO_YEAR_COMPATIBLE_REFERENCE">Búsqueda</a></td></tr>`).join("");
return html("SUPERBID — Referencias Fasecolda por año",`<header class="top"><div><div class="ey">SUPERBID · v0.39</div><h1>Diagnóstico Fasecolda por año</h1></div>${nav}</header><main><div class="notice"><strong>FASECOLDA_YEAR_REFERENCE_DIAGNOSTIC_NOT_VALUATION.</strong> Los valores inferior/superior son observaciones Fasecolda de otros años. No se interpolan, no se trasladan al año del lote, no crean homologación y no modifican puja máxima ni decisión.</div><section class="metrics">${cards}</section><section class="panel"><div class="head"><div><h2>${xs.length} casos visibles</h2><span class="sub">Primero identidad de marca; luego brechas entre años; finalmente cobertura de fuente.</span></div>${filter}</div><div class="tablewrap"><table><thead><tr><th>Rank</th><th>Diagnóstico</th><th>Vehículo</th><th>Año lote</th><th>Marca</th><th>Línea buscada</th><th>Años disponibles</th><th>Referencia inferior</th><th>Referencia superior</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows||'<tr><td colspan="11">Sin casos para estos filtros.</td></tr>'}</tbody></table></div></section></main>`)}
Deno.serve(async req=>{const p=pathOf(req);if(req.method==="POST"&&p==="/login"){const f=await req.formData(),pw=String(f.get("password")||"");if(!await valid(pw))return login(true);return new Response("",{status:303,headers:{location:"/functions/v1/superbid-fasecolda-year-dashboard","set-cookie":`${COOKIE}=${encodeURIComponent(pw)}; Path=/functions/v1/superbid-fasecolda-year-dashboard; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`}})}if(req.method==="POST"&&p==="/logout")return new Response("",{status:303,headers:{location:"/functions/v1/superbid-fasecolda-year-dashboard","set-cookie":`${COOKIE}=; Path=/functions/v1/superbid-fasecolda-year-dashboard; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}});if(!await valid(cookie(req)))return login(false);if(req.method!=="GET")return html("Error","<main>Método no permitido.</main>",405);if(p==="/"||p==="")return board(req);return html("No encontrado","<main>Ruta no encontrada.</main>",404)});
