import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const j=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
async function db(path:string,init:RequestInit={}){return fetch(`${U}${path}`,{...init,headers:{apikey:K,authorization:`Bearer ${K}`,"content-type":"application/json",...(init.headers||{})}})}
async function auth(req:Request){const a=req.headers.get("authorization")||"";const t=a.toLowerCase().startsWith("bearer ")?a.slice(7).trim():(req.headers.get("x-superbid-read-key")||"").trim();if(!t||t.length>256)return false;const r=await db("/rest/v1/rpc/dashboard_token_valid",{method:"POST",body:JSON.stringify({p_token:t})});return r.ok&&(await r.json())===true}
const n=(v:string|null,d:number,m:number)=>{const x=parseInt(v||"",10);return Number.isFinite(x)?Math.max(1,Math.min(m,x)):d};
const csvCell=(v:any)=>{if(v==null)return "";const s=String(v);return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{allow:"GET,OPTIONS"}});if(req.method!=="GET")return j({error:"method_not_allowed"},405);if(!await auth(req))return j({error:"unauthorized"},401);const u=new URL(req.url),m="/superbid-read-api",i=u.pathname.indexOf(m),p=i>=0?(u.pathname.slice(i+m.length)||"/"):u.pathname;
if(p==="/health")return j({ok:true,service:"superbid-read-api",version:"0.29"});
if(p==="/summary"){const r=await db("/rest/v1/rpc/dashboard_summary",{method:"POST",body:"{}"});return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
if(p==="/alerts"){const lim=n(u.searchParams.get("limit"),100,500),ty=(u.searchParams.get("type")||"").toUpperCase(),sv=(u.searchParams.get("severity")||"").toUpperCase(),op=(u.searchParams.get("open")||"").toLowerCase(),active=(u.searchParams.get("system_active")||"").toLowerCase(),disp=(u.searchParams.get("disposition")||"").toUpperCase();const types=new Set(["CLOSING_2H","HIGH_PRESSURE","CLOSE_EXTENSION"]),severities=new Set(["URGENT","WARNING","INFO"]),dispositions=new Set(["ACKNOWLEDGED","DISMISSED"]);const sel="id,external_lot_id,alert_type,severity,triggered_at,source_observed_at,title,current_bid_cop,closes_at,review_state,pressure_level,operational_rank,preliminary_headroom_cop,peritaje_count,message,evidence,interpretation,acknowledged_at,acknowledged_note,is_open,manual_disposition,system_resolved_at,system_resolution_reason,is_unattended,is_system_active";let q=`/rest/v1/dashboard_operational_alert_feed?select=${encodeURIComponent(sel)}&order=source_observed_at.desc.nullslast,triggered_at.desc&limit=${lim}`;if(types.has(ty))q+=`&alert_type=eq.${encodeURIComponent(ty)}`;if(severities.has(sv))q+=`&severity=eq.${encodeURIComponent(sv)}`;if(op==="true"||op==="false")q+=`&is_open=eq.${op}`;if(active==="true"||active==="false")q+=`&is_system_active=eq.${active}`;if(dispositions.has(disp))q+=`&manual_disposition=eq.${encodeURIComponent(disp)}`;const r=await db(q);return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
if(p==="/peritaje-reviews"){const lim=n(u.searchParams.get("limit"),100,500),st=(u.searchParams.get("status")||"").toUpperCase(),rs=(u.searchParams.get("review_state")||"").toUpperCase();const statuses=new Set(["UNREVIEWED","DRAFT","REVIEWED"]),states=new Set(["REVIEW_NOW","REVIEW_SOON","WATCH","NO_HEADROOM","BLOCKED_VALUATION","CLOSED_OR_PAST"]);const sel="external_lot_id,lot_id,title,city,seller,current_bid_cop,closes_at,review_state,review_score,peritaje_count,peritajes,preliminary_headroom_before_fixed_costs_cop,peritaje_review_status,source_attachment_url,mechanical_risk,transmission_risk,body_risk,safety_risk,electrical_risk,tires_risk,documentation_risk,missing_parts_risk,overall_risk,repair_low_cop,repair_base_cop,repair_high_cop,notes,reviewed_at,updated_at,interpretation";let q=`/rest/v1/dashboard_peritaje_review_current?select=${encodeURIComponent(sel)}&order=review_score.desc,closes_at.asc&limit=${lim}`;if(statuses.has(st))q+=`&peritaje_review_status=eq.${encodeURIComponent(st)}`;if(states.has(rs))q+=`&review_state=eq.${encodeURIComponent(rs)}`;const r=await db(q);return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
const prm=p.match(/^\/lots\/(\d{5,12})\/peritaje-review$/);if(prm){const r=await db(`/rest/v1/dashboard_peritaje_review_current?select=*&external_lot_id=eq.${prm[1]}&limit=1`);if(!r.ok)return new Response(await r.text(),{status:r.status});const a=await r.json();return a.length?j(a[0]):j({error:"not_found_or_no_peritaje"},404)}
if(p==="/operational-queue"){const lim=n(u.searchParams.get("limit"),100,500),st=(u.searchParams.get("state")||"").toUpperCase(),pr=(u.searchParams.get("pressure")||"").toUpperCase(),cl=(u.searchParams.get("closing")||"").toUpperCase();const states=new Set(["REVIEW_NOW","REVIEW_SOON","WATCH","NO_HEADROOM","BLOCKED_VALUATION","CLOSED_OR_PAST"]),pressures=new Set(["HIGH","MEDIUM","LOW","NONE"]),closings=new Set(["CLOSING_2H","CLOSING_6H","CLOSING_24H","LATER","PAST","NO_CLOSE_TIME"]);const sel="external_lot_id,title,brand,line,model_year,city,seller,url,current_bid_cop,bid_count,closes_at,hours_to_close,outcome,commission_percent_public,fasecolda_status,fasecolda_current_cop,preliminary_headroom_before_fixed_costs_cop,peritaje_count,review_score,review_state,market_status,max_bid_market_validated_cop,expected_profit_current_cop,expected_roi_current_pct,final_decision,pressure_level,pressure_changes_2h,pressure_bid_up_2h,pressure_price_up_2h_cop,close_extension_count,pressure_last_change_at,closing_bucket,operational_rank,operational_reason,operational_interpretation";let q=`/rest/v1/dashboard_operational_queue?select=${encodeURIComponent(sel)}&order=operational_rank.asc,review_score.desc,closes_at.asc&limit=${lim}`;if(states.has(st))q+=`&review_state=eq.${encodeURIComponent(st)}`;if(pressures.has(pr))q+=`&pressure_level=eq.${encodeURIComponent(pr)}`;if(closings.has(cl))q+=`&closing_bucket=eq.${encodeURIComponent(cl)}`;const r=await db(q);return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
if(p==="/review-queue"){const lim=n(u.searchParams.get("limit"),100,500),st=(u.searchParams.get("state")||"").toUpperCase(),ok=new Set(["REVIEW_NOW","REVIEW_SOON","WATCH","NO_HEADROOM","BLOCKED_VALUATION","CLOSED_OR_PAST"]);const sel="external_lot_id,title,brand,line,model_year,city,seller,url,current_bid_cop,bid_count,closes_at,outcome,commission_percent_public,fasecolda_status,fasecolda_current_cop,fasecolda_12m_ago_cop,fasecolda_change_12m_pct,preliminary_headroom_before_fixed_costs_cop,peritaje_count,peritajes,review_score,review_state,review_reasons,market_status,market_comparable_count_live,market_quick_sale_cop,max_bid_market_validated_cop,expected_profit_current_cop,expected_roi_current_pct,market_final_buy_recommendation_available,final_decision";let q=`/rest/v1/dashboard_lot_current?select=${encodeURIComponent(sel)}&order=review_score.desc,closes_at.asc&limit=${lim}`;if(ok.has(st))q+=`&review_state=eq.${encodeURIComponent(st)}`;const r=await db(q);return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
const pm=p.match(/^\/lots\/(\d{5,12})\/bid-pressure$/);if(pm){const r=await db("/rest/v1/rpc/dashboard_bid_pressure",{method:"POST",body:JSON.stringify({p_external_lot_id:pm[1]})});return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
const em=p.match(/^\/lots\/(\d{5,12})\/observed-bid-events$/);if(em){const r=await db("/rest/v1/rpc/dashboard_observed_bid_events",{method:"POST",body:JSON.stringify({p_external_lot_id:em[1]})});return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
const tm=p.match(/^\/lots\/(\d{5,12})\/timeline$/);if(tm){const r=await db("/rest/v1/rpc/dashboard_lot_timeline",{method:"POST",body:JSON.stringify({p_external_lot_id:tm[1]})});return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
const lm=p.match(/^\/lots\/(\d{5,12})$/);if(lm){const r=await db(`/rest/v1/dashboard_lot_current?select=*&external_lot_id=eq.${lm[1]}&limit=1`);if(!r.ok)return new Response(await r.text(),{status:r.status});const a=await r.json();return a.length?j(a[0]):j({error:"not_found"},404)}
if(p==="/history"){const lim=n(u.searchParams.get("limit"),300,1000);const r=await db(`/rest/v1/dashboard_history_export?select=*&order=last_seen_at.desc&limit=${lim}`);return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json","cache-control":"no-store"}})}
if(p==="/export/history.csv"){const r=await db("/rest/v1/dashboard_history_export?select=external_lot_id,title,brand,line,version,model_year,city,seller,initial_bid_cop,outcome,closing_price_observed_cop,sale_price_confirmed_cop,historical_value_cop,historical_value_type,confidence,confirmation_source,snapshot_count,peritaje_count,fasecolda_status,fasecolda_code,fasecolda_current_cop,fasecolda_confidence,first_seen_at,last_seen_at,url&order=last_seen_at.desc&limit=10000");if(!r.ok)return j({error:"export_failed"},500);const rows=await r.json(),headers=["external_lot_id","title","brand","line","version","model_year","city","seller","initial_bid_cop","outcome","closing_price_observed_cop","sale_price_confirmed_cop","historical_value_cop","historical_value_type","confidence","confirmation_source","snapshot_count","peritaje_count","fasecolda_status","fasecolda_code","fasecolda_current_cop","fasecolda_confidence","first_seen_at","last_seen_at","url"];const body="\ufeff"+headers.join(",")+"\n"+rows.map((x:any)=>headers.map(h=>csvCell(x[h])).join(",")).join("\n");return new Response(body,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=superbid_historico.csv","cache-control":"no-store"}})}
return j({error:"not_found"},404)});