import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,COOKIE="sb_fasecolda_workbench_session";
const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]||m));
const cop=(v:any)=>v==null?"—":new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(Number(v));
const dt=(v:any)=>v?new Intl.DateTimeFormat("es-CO",{timeZone:"America/Bogota",dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const css=`:root{--bg:#f4f6f3;--p:#fff;--t:#182018;--m:#687168;--l:#dfe5de;--g:#123d2a;--g2:#1f6a49;--a:#765400;--r:#842828}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--t);font:14px/1.45 Inter,system-ui,sans-serif}a{text-decoration:none;color:inherit}.top{background:var(--g);color:#fff;padding:18px 26px;display:flex;justify-content:space-between;gap:14px;align-items:center}.top h1{margin:2px 0}.ey{font-size:10px;letter-spacing:1.4px;font-weight:800;opacity:.7}main{padding:20px 26px 45px;max-width:1720px;margin:auto}.nav,.filters,.badges{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.btn,button,select{border:1px solid var(--l);border-radius:8px;padding:8px 10px;background:#fff;font:inherit;font-weight:700}.btn,button{cursor:pointer}.btn.primary,button.primary{background:var(--g2);border-color:var(--g2);color:#fff}.notice{padding:12px 14px;border:1px solid #ead99c;background:#fff3cf;color:#65490d;border-radius:10px;margin-bottom:14px}.panel,.metric{background:var(--p);border:1px solid var(--l);border-radius:13px}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.metric{padding:14px}.metric span,.sub{display:block;color:var(--m);font-size:11px}.metric strong{font-size:23px}.head{padding:15px 17px;border-bottom:1px solid var(--l);display:flex;justify-content:space-between;gap:10px;align-items:center}.head h2{margin:0}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1450px}th,td{padding:9px 10px;border-bottom:1px solid #edf0ec;text-align:left;vertical-align:top;white-space:nowrap}th{font-size:10px;text-transform:uppercase;color:var(--m);background:#fafbf9;position:sticky;top:0}.vehicle{white-space:normal;min-width:290px}.reason{white-space:normal;min-width:240px;max-width:320px}.pill{font-size:10px;font-weight:800;border-radius:99px;padding:5px 8px;display:inline-block}.candidate{background:#fff0c9;color:var(--a)}.search{background:#daf0e1;color:#175935}.year{background:#e8eef3;color:#425c70}.other{background:#ecefec;color:#586158}.high{background:#daf0e1;color:#175935}.ambiguous{background:#fff0c9;color:var(--a)}.unmatched{background:#f4e5e5;color:var(--r)}.medium{background:#e8eef3;color:#425c70}.rank{font-size:18px;font-weight:900}.login{width:min(430px,92vw);margin:15vh auto;background:#fff;border:1px solid var(--l);border-radius:16px;padding:28px}.login input{width:100%;border:1px solid var(--l);border-radius:8px;padding:9px}.login button{width:100%;margin-top:10px}.err{color:var(--r);font-weight:700}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}main{padding:13px}.top{align-items:flex-start}}`;
function html(title:string,body:string,status=200,headers:Record<string,string>={}){return new Response(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${css}</style></head><body>${body}</body></html>`,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store",...headers}})}
async function db(path:string,init:RequestInit={}){return fetch(`${U}${path}`,{...init,headers:{apikey:K,authorization:`Bearer ${K}`,"content-type":"application/json",...(init.headers||{})}})}
function cookie(req:Request){for(const p of (req.headers.get("cookie")||"").split(";")){const [k,...v]=p.trim().split("=");if(k===COOKIE)return decodeURIComponent(v.join("="))}return ""}
async function valid(t:string){if(!t||t.length<32||t.length>256)return false;const r=await db("/rest/v1/rpc/dashboard_token_valid",{method:"POST",body:JSON.stringify({p_token:t})});return r.ok&&(await r.json())===true}
function pathOf(req:Request){const p=new URL(req.url).pathname,m="/superbid-fasecolda-workbench",i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||"/"):p}
function login(error=false){return html("SUPERBID — Fasecolda Workbench",`<form class="login" method="post" action="/functions/v1/superbid-fasecolda-workbench/login"><div class="ey">SUPERBID</div><h1>Fasecolda Workbench</h1><p class="sub">Acceso privado. Esta capa solo organiza casos; no homologa vehículos.</p>${error?'<p class="err">Credencial inválida.</p>':''}<input type="password" name="password" autocomplete="current-password" required placeholder="Clave de acceso"><button class="primary">Entrar</button></form>`,error?401:200)}
const nav=`<nav class="nav"><a class="btn" href="/functions/v1/superbid-dashboard">Dashboard</a><a class="btn" href="/functions/v1/superbid-readiness-dashboard">Readiness</a><a class="btn" href="/functions/v1/superbid-fasecolda-dashboard">Resolver candidatos</a><a class="btn" href="/functions/v1/superbid-fasecolda-search-dashboard">Términos de búsqueda</a><a class="btn" href="/functions/v1/superbid-fasecolda-year-dashboard">Referencias por año</a><form method="post" action="/functions/v1/superbid-fasecolda-workbench/logout"><button>Salir</button></form></nav>`;
function option(v:string,label:string,current:string){return `<option value="${esc(v)}" ${v===current?"selected":""}>${esc(label)}</option>`}
function workflowPill(v:string){const c=v==="CANDIDATE_RESOLUTION"?"candidate":v==="SEARCH_TERM_WORKFLOW"?"search":v==="YEAR_REFERENCE_REVIEW"?"year":"other";return `<span class="pill ${c}">${esc(v)}</span>`}
function statusPill(v:string){const x=String(v||"NO_MATCH_ROW"),c=x==="HIGH"?"high":x==="AMBIGUOUS"?"ambiguous":x==="MEDIUM"?"medium":"unmatched";return `<span class="pill ${c}">${esc(x)}</span>`}
function workflowUrl(x:any){if(x.workflow_target==="CANDIDATE_RESOLUTION")return `/functions/v1/superbid-fasecolda-dashboard?automatic_status=${encodeURIComponent(x.effective_status||"AMBIGUOUS")}&manual_status=UNRESOLVED`;if(x.workflow_target==="YEAR_REFERENCE_REVIEW")return "/functions/v1/superbid-fasecolda-year-dashboard";if(x.workflow_target==="SEARCH_TERM_WORKFLOW")return `/functions/v1/superbid-fasecolda-search-dashboard?reason=${encodeURIComponent(x.diagnostic_reason||"ALL")}`;return "/functions/v1/superbid-readiness-dashboard"}
async function board(req:Request){const u=new URL(req.url),workflow=(u.searchParams.get("workflow")||"ALL").toUpperCase(),state=(u.searchParams.get("review_state")||"ALL").toUpperCase();const workflows=new Set(["CANDIDATE_RESOLUTION","SEARCH_TERM_WORKFLOW","YEAR_REFERENCE_REVIEW","VALUATION_REVIEW_OTHER","ALL"]),states=new Set(["REVIEW_NOW","REVIEW_SOON","WATCH","NO_HEADROOM","BLOCKED_VALUATION","CLOSED_OR_PAST","ALL"]),wf=workflows.has(workflow)?workflow:"ALL",rs=states.has(state)?state:"ALL";
const countSel="workflow_target,triage_rank";const cr=await db(`/rest/v1/dashboard_fasecolda_valuation_workbench?select=${encodeURIComponent(countSel)}&limit=500`);if(!cr.ok)return html("Error","<main>No fue posible consultar el workbench.</main>",500);const all=await cr.json();const counts={CANDIDATE_RESOLUTION:0,SEARCH_TERM_WORKFLOW:0,YEAR_REFERENCE_REVIEW:0,VALUATION_REVIEW_OTHER:0};for(const x of all){if(x.workflow_target in counts)counts[x.workflow_target as keyof typeof counts]++}
const sel="external_lot_id,title,brand,line,model_year,city,seller,current_bid_cop,closes_at,hours_to_close,review_state,review_score,effective_status,automatic_status,match_origin,search_term,search_term_origin,candidate_count,manual_resolution_status,diagnostic_reason,current_search_term,suggested_search_term,suggestion_differs,workflow_target,triage_rank,triage_reason,workflow_function,interpretation";let q=`/rest/v1/dashboard_fasecolda_valuation_workbench?select=${encodeURIComponent(sel)}&order=triage_rank.asc,review_score.desc,closes_at.asc&limit=300`;if(wf!=="ALL")q+=`&workflow_target=eq.${encodeURIComponent(wf)}`;if(rs!=="ALL")q+=`&review_state=eq.${encodeURIComponent(rs)}`;const r=await db(q);if(!r.ok)return html("Error","<main>No fue posible consultar casos de valoración.</main>",500);const xs=await r.json();
const cards=[["Bloqueos valoración",all.length],["Resolver candidatos",counts.CANDIDATE_RESOLUTION],["Revisar búsqueda",counts.SEARCH_TERM_WORKFLOW],["Revisar año",counts.YEAR_REFERENCE_REVIEW],["Otros",counts.VALUATION_REVIEW_OTHER]].map(x=>`<div class="metric"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join("");
const filter=`<form class="filters" method="get"><select name="workflow">${option("ALL","Todos los workflows",wf)}${option("CANDIDATE_RESOLUTION","Resolver candidatos",wf)}${option("SEARCH_TERM_WORKFLOW","Revisar término",wf)}${option("YEAR_REFERENCE_REVIEW","Revisar referencia/año",wf)}${option("VALUATION_REVIEW_OTHER","Otros",wf)}</select><select name="review_state">${option("ALL","Todos los estados",rs)}${option("REVIEW_NOW","Revisar ahora",rs)}${option("REVIEW_SOON","Revisar pronto",rs)}${option("WATCH","Vigilar",rs)}${option("BLOCKED_VALUATION","Bloqueado valoración",rs)}</select><button class="primary">Aplicar</button></form>`;
const rows=xs.map((x:any)=>`<tr><td><span class="rank">${esc(x.triage_rank)}</span></td><td>${workflowPill(x.workflow_target)}</td><td class="vehicle"><strong>${esc(x.title)}</strong><div class="sub">Lote ${esc(x.external_lot_id)} · ${esc([x.city,x.seller].filter(Boolean).join(" · "))}</div></td><td>${esc(x.model_year??"—")}</td><td>${statusPill(x.effective_status)}<div class="sub">origen: ${esc(x.match_origin||"—")}</div></td><td>${esc(x.candidate_count??0)}</td><td>${esc(x.diagnostic_reason||"—")}</td><td class="reason">${esc(x.triage_reason)}</td><td>${cop(x.current_bid_cop)}</td><td>${dt(x.closes_at)}</td><td>${esc(x.review_state)}</td><td><a class="btn primary" href="${esc(workflowUrl(x))}">Abrir workflow</a> <a class="btn" href="/functions/v1/superbid-dashboard/lots/${esc(x.external_lot_id)}">Lote</a></td></tr>`).join("");
return html("SUPERBID — Fasecolda Workbench",`<header class="top"><div><div class="ey">SUPERBID · v0.39</div><h1>Fasecolda Valuation Workbench</h1></div>${nav}</header><main><div class="notice"><strong>FASECOLDA_VALUATION_TRIAGE_NOT_MATCH.</strong> Esta cola solo decide qué workflow humano abrir. No confirma candidatos, no cambia términos, no fuerza HIGH y no modifica puja máxima ni decisión de compra.</div><section class="metrics">${cards}</section><section class="panel"><div class="head"><div><h2>${xs.length} casos visibles</h2><span class="sub">Orden: tipo de trabajo, score de revisión y cierre. Rank 10 prioriza casos con 1–3 candidatos públicos.</span></div>${filter}</div><div class="tablewrap"><table><thead><tr><th>Rank</th><th>Workflow</th><th>Vehículo</th><th>Año</th><th>Fasecolda</th><th>Candidatos</th><th>Diagnóstico</th><th>Razón</th><th>Puja</th><th>Cierre</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows||'<tr><td colspan="12">Sin casos para estos filtros.</td></tr>'}</tbody></table></div></section></main>`)}
Deno.serve(async req=>{const p=pathOf(req);if(req.method==="POST"&&p==="/login"){const f=await req.formData(),pw=String(f.get("password")||"");if(!await valid(pw))return login(true);return new Response("",{status:303,headers:{location:"/functions/v1/superbid-fasecolda-workbench","set-cookie":`${COOKIE}=${encodeURIComponent(pw)}; Path=/functions/v1/superbid-fasecolda-workbench; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`}})}if(req.method==="POST"&&p==="/logout")return new Response("",{status:303,headers:{location:"/functions/v1/superbid-fasecolda-workbench","set-cookie":`${COOKIE}=; Path=/functions/v1/superbid-fasecolda-workbench; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}});if(!await valid(cookie(req)))return login(false);if(req.method!=="GET")return html("Error","<main>Método no permitido.</main>",405);if(p==="/"||p==="")return board(req);return html("No encontrado","<main>Ruta no encontrada.</main>",404)});
