create table if not exists public.peritaje_repair_cost_transfer_history(
  id bigint generated by default as identity primary key,
  lot_id bigint not null references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  peritaje_review_id bigint not null references public.lot_peritaje_reviews(id) on delete restrict,
  peritaje_reviewed_at timestamptz not null,
  source_attachment_url text,
  scenario text not null check(scenario in ('LOW','BASE','HIGH')),
  selected_repair_cop bigint not null check(selected_repair_cop>=0 and selected_repair_cop<=50000000000),
  previous_repair_cop bigint,
  note text,
  created_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'MANUAL_PERITAJE_COST_TRANSFER_NOT_AUTOMATIC' check(interpretation='MANUAL_PERITAJE_COST_TRANSFER_NOT_AUTOMATIC'),
  constraint peritaje_repair_cost_transfer_note_len check(note is null or char_length(note)<=2000)
);

create index if not exists idx_peritaje_repair_transfer_lot_created
  on public.peritaje_repair_cost_transfer_history(lot_id,created_at desc);

alter table public.peritaje_repair_cost_transfer_history enable row level security;
revoke all on public.peritaje_repair_cost_transfer_history from public,anon,authenticated;
grant select,insert on public.peritaje_repair_cost_transfer_history to service_role;

create or replace function public.dashboard_transfer_peritaje_repair_to_costs(
  p_external_lot_id text,
  p_scenario text,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_lot_id bigint;
  v_review public.lot_peritaje_reviews%rowtype;
  v_scenario text;
  v_selected bigint;
  v_previous bigint;
  v_cost public.lot_cost_overrides%rowtype;
begin
  if p_external_lot_id is null or p_external_lot_id !~ '^\d{5,12}$' then
    raise exception 'invalid external lot id';
  end if;
  v_scenario:=upper(trim(coalesce(p_scenario,'')));
  if v_scenario not in ('LOW','BASE','HIGH') then
    raise exception 'invalid repair scenario';
  end if;
  if p_note is not null and char_length(p_note)>2000 then
    raise exception 'note too long';
  end if;

  select id into v_lot_id
  from public.auction_lots
  where external_lot_id=p_external_lot_id
  order by id desc limit 1;
  if v_lot_id is null then raise exception 'lot not found'; end if;

  select * into v_review
  from public.lot_peritaje_reviews
  where lot_id=v_lot_id
  limit 1;
  if v_review.id is null or v_review.reviewed_at is null then
    raise exception 'peritaje review must be explicitly reviewed before transfer';
  end if;

  v_selected:=case v_scenario
    when 'LOW' then v_review.repair_low_cop::bigint
    when 'BASE' then v_review.repair_base_cop::bigint
    when 'HIGH' then v_review.repair_high_cop::bigint
  end;
  if v_selected is null then raise exception 'selected repair scenario has no value'; end if;
  if v_selected<0 or v_selected>50000000000 then raise exception 'selected repair value outside allowed range'; end if;

  select * into v_cost from public.lot_cost_overrides where lot_id=v_lot_id limit 1;
  v_previous:=v_cost.repair_cop;

  if v_cost.lot_id is null then
    insert into public.lot_cost_overrides(
      lot_id,repair_cop,reviewed_at,updated_at
    ) values(
      v_lot_id,v_selected,null,clock_timestamp()
    );
  else
    update public.lot_cost_overrides
    set repair_cop=v_selected,
        reviewed_at=null,
        updated_at=clock_timestamp()
    where lot_id=v_lot_id;
  end if;

  select * into v_cost from public.lot_cost_overrides where lot_id=v_lot_id limit 1;

  insert into public.lot_cost_review_history(
    lot_id,transfer_cop,taxes_soat_cop,transport_cop,repair_cop,detailing_cop,
    financing_cop,admin_fee_cop,contingency_cop,source_note,marked_reviewed,reviewed_at
  ) values(
    v_lot_id,v_cost.transfer_cop,v_cost.taxes_soat_cop,v_cost.transport_cop,v_cost.repair_cop,v_cost.detailing_cop,
    v_cost.financing_cop,v_cost.admin_fee_cop,v_cost.contingency_cop,v_cost.source_note,false,null
  );

  insert into public.peritaje_repair_cost_transfer_history(
    lot_id,external_lot_id,peritaje_review_id,peritaje_reviewed_at,source_attachment_url,
    scenario,selected_repair_cop,previous_repair_cop,note
  ) values(
    v_lot_id,p_external_lot_id,v_review.id,v_review.reviewed_at,v_review.source_attachment_url,
    v_scenario,v_selected,v_previous,nullif(trim(coalesce(p_note,'')),'')
  );

  return jsonb_build_object(
    'ok',true,
    'external_lot_id',p_external_lot_id,
    'scenario',v_scenario,
    'repair_cop',v_selected,
    'previous_repair_cop',v_previous,
    'cost_review_invalidated',true,
    'interpretation','MANUAL_PERITAJE_COST_TRANSFER_NOT_AUTOMATIC'
  );
end;
$$;

revoke all on function public.dashboard_transfer_peritaje_repair_to_costs(text,text,text) from public,anon,authenticated;
grant execute on function public.dashboard_transfer_peritaje_repair_to_costs(text,text,text) to service_role;

create or replace view public.dashboard_cost_readiness_current as
select
  p.external_lot_id,
  p.lot_id,
  p.title,
  p.city,
  p.seller,
  p.current_bid_cop,
  p.closes_at,
  p.review_state,
  p.review_score,
  p.peritaje_review_status,
  p.overall_risk,
  p.repair_low_cop,
  p.repair_base_cop,
  p.repair_high_cop,
  p.reviewed_at as peritaje_reviewed_at,
  c.transfer_cop,
  c.taxes_soat_cop,
  c.transport_cop,
  c.repair_cop,
  c.detailing_cop,
  c.financing_cop,
  c.admin_fee_cop,
  c.contingency_cop,
  c.reviewed_at as costs_reviewed_at,
  case
    when c.lot_id is null then 'NO_COSTS'
    when c.reviewed_at is not null then 'REVIEWED'
    else 'DRAFT'
  end as cost_review_status,
  ((c.transfer_cop is not null)::int +
   (c.taxes_soat_cop is not null)::int +
   (c.transport_cop is not null)::int +
   (c.repair_cop is not null)::int +
   (c.detailing_cop is not null)::int +
   (c.financing_cop is not null)::int +
   (c.admin_fee_cop is not null)::int +
   (c.contingency_cop is not null)::int) as completed_cost_fields,
  case
    when c.repair_cop is null then 'NOT_TRANSFERRED'
    when p.repair_low_cop is not null and c.repair_cop=p.repair_low_cop then 'MATCH_LOW'
    when p.repair_base_cop is not null and c.repair_cop=p.repair_base_cop then 'MATCH_BASE'
    when p.repair_high_cop is not null and c.repair_cop=p.repair_high_cop then 'MATCH_HIGH'
    else 'CUSTOM'
  end as repair_cost_source_status,
  (p.peritaje_review_status='REVIEWED') as peritaje_ready_for_cost_transfer,
  'MANUAL_PERITAJE_COST_TRANSFER_NOT_AUTOMATIC'::text as interpretation
from public.dashboard_peritaje_review_current p
left join public.lot_cost_overrides c using(lot_id);

revoke all on public.dashboard_cost_readiness_current from public,anon,authenticated;
grant select on public.dashboard_cost_readiness_current to service_role;