create table if not exists public.lot_fasecolda_search_term_overrides (
  lot_id bigint primary key references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  search_term text not null check (char_length(search_term) between 2 and 80),
  note text check (note is null or char_length(note)<=2000),
  confirmed_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH',
  constraint lot_fasecolda_search_term_overrides_interpretation_check
    check (interpretation='MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH')
);

create table if not exists public.lot_fasecolda_search_term_override_history (
  id bigint generated by default as identity primary key,
  lot_id bigint not null references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  action text not null check (action in ('CONFIRM','CLEAR','INVALIDATE_IDENTITY_CHANGE')),
  previous_search_term text,
  new_search_term text,
  previous_match_status text,
  previous_best_code text,
  previous_best_description text,
  previous_value_cop bigint,
  result_match_status text,
  result_best_code text,
  result_best_description text,
  result_value_cop bigint,
  note text check (note is null or char_length(note)<=2000),
  created_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH',
  constraint lot_fasecolda_search_term_override_history_interpretation_check
    check (interpretation='MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH')
);

alter table public.lot_fasecolda_search_term_overrides enable row level security;
alter table public.lot_fasecolda_search_term_override_history enable row level security;
revoke all on public.lot_fasecolda_search_term_overrides from public,anon,authenticated;
revoke all on public.lot_fasecolda_search_term_override_history from public,anon,authenticated;
grant select,insert,update,delete on public.lot_fasecolda_search_term_overrides to service_role;
grant select,insert on public.lot_fasecolda_search_term_override_history to service_role;
create index if not exists idx_fasecolda_search_override_history_lot_created
  on public.lot_fasecolda_search_term_override_history(lot_id,created_at desc);

create or replace function public.fasecolda_effective_search_term(p_lot_id bigint,p_title text)
returns text
language sql
stable
security definer
set search_path to 'public','pg_catalog'
as $function$
  select coalesce(
    (select o.search_term from public.lot_fasecolda_search_term_overrides o where o.lot_id=p_lot_id),
    public.fasecolda_search_term(p_title)
  );
$function$;
revoke all on function public.fasecolda_effective_search_term(bigint,text) from public,anon,authenticated;
grant execute on function public.fasecolda_effective_search_term(bigint,text) to service_role;

-- Preserve the existing matcher and patch only its search-term source.
do $patch$
declare
  v_def text;
  v_old constant text := 'v_term := public.fasecolda_search_term(v_lot.title);';
  v_new constant text := 'v_term := public.fasecolda_effective_search_term(p_lot_id,v_lot.title);';
begin
  select pg_get_functiondef('public.fasecolda_match_lot(bigint,boolean)'::regprocedure) into v_def;
  if position(v_old in v_def)=0 then raise exception 'fasecolda_match_lot patch anchor not found'; end if;
  if length(v_def)-length(replace(v_def,v_old,'')) <> length(v_old) then
    raise exception 'fasecolda_match_lot patch anchor is not unique';
  end if;
  execute replace(v_def,v_old,v_new);
end;
$patch$;

create or replace function public.dashboard_set_fasecolda_search_term_override(
  p_external_lot_id text,
  p_action text,
  p_term text default null,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public','extensions','pg_catalog'
as $function$
declare
  v_lot public.auction_lots%rowtype;
  v_prev_override public.lot_fasecolda_search_term_overrides%rowtype;
  v_prev_match public.lot_fasecolda_matches%rowtype;
  v_result_match public.lot_fasecolda_matches%rowtype;
  v_had_override boolean := false;
  v_action text := upper(trim(coalesce(p_action,'')));
  v_term text;
  v_brand text;
  v_note text := nullif(trim(coalesce(p_note,'')),'');
  v_probe jsonb;
  v_match jsonb;
begin
  if p_external_lot_id is null or p_external_lot_id !~ '^\d{5,12}$' then raise exception 'invalid external lot id'; end if;
  if v_action not in ('CONFIRM','CLEAR') then raise exception 'invalid search term override action'; end if;
  if v_note is not null and char_length(v_note)>2000 then raise exception 'note too long'; end if;

  select * into v_lot from public.auction_lots where external_lot_id=p_external_lot_id order by id desc limit 1;
  if not found then raise exception 'lot not found'; end if;

  if exists(select 1 from public.lot_fasecolda_manual_resolutions mr where mr.lot_id=v_lot.id) then
    raise exception 'clear manual Fasecolda candidate resolution before changing search term';
  end if;

  select * into v_prev_override from public.lot_fasecolda_search_term_overrides where lot_id=v_lot.id;
  v_had_override := found;
  select * into v_prev_match from public.lot_fasecolda_matches where lot_id=v_lot.id;

  if v_action='CLEAR' then
    if not v_had_override then raise exception 'search term override not found'; end if;
    delete from public.lot_fasecolda_search_term_overrides where lot_id=v_lot.id;
    v_match := public.fasecolda_match_lot(v_lot.id,true);
    select * into v_result_match from public.lot_fasecolda_matches where lot_id=v_lot.id;
    insert into public.lot_fasecolda_search_term_override_history(
      lot_id,external_lot_id,action,previous_search_term,new_search_term,
      previous_match_status,previous_best_code,previous_best_description,previous_value_cop,
      result_match_status,result_best_code,result_best_description,result_value_cop,note
    ) values(
      v_lot.id,v_lot.external_lot_id,'CLEAR',v_prev_override.search_term,public.fasecolda_search_term(v_lot.title),
      v_prev_match.status,v_prev_match.best_code,v_prev_match.best_description,v_prev_match.current_value_cop,
      v_result_match.status,v_result_match.best_code,v_result_match.best_description,v_result_match.current_value_cop,v_note
    );
    return jsonb_build_object('ok',true,'action','CLEAR','matcher_result',v_match,'match_origin','AUTOMATIC','interpretation','MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH');
  end if;

  v_term := trim(public.vehicle_norm(coalesce(p_term,'')));
  if char_length(v_term)<2 or char_length(v_term)>80 then raise exception 'invalid search term length'; end if;
  v_brand := nullif(trim(public.vehicle_norm(coalesce(v_lot.brand,''))),'');
  if v_brand is not null and not (v_term=v_brand or v_term like v_brand||' %') then raise exception 'search term must preserve vehicle brand'; end if;

  v_probe := public.dashboard_probe_fasecolda_search_term(v_lot.external_lot_id,v_term);
  if not coalesce((v_probe->>'has_codes')::boolean,false) then raise exception 'search term probe returned no public Fasecolda codes'; end if;

  insert into public.lot_fasecolda_search_term_overrides(lot_id,external_lot_id,search_term,note,confirmed_at,updated_at)
  values(v_lot.id,v_lot.external_lot_id,v_term,v_note,clock_timestamp(),clock_timestamp())
  on conflict(lot_id) do update set search_term=excluded.search_term,note=excluded.note,confirmed_at=excluded.confirmed_at,updated_at=excluded.updated_at;

  v_match := public.fasecolda_match_lot(v_lot.id,true);
  select * into v_result_match from public.lot_fasecolda_matches where lot_id=v_lot.id;

  insert into public.lot_fasecolda_search_term_override_history(
    lot_id,external_lot_id,action,previous_search_term,new_search_term,
    previous_match_status,previous_best_code,previous_best_description,previous_value_cop,
    result_match_status,result_best_code,result_best_description,result_value_cop,note
  ) values(
    v_lot.id,v_lot.external_lot_id,'CONFIRM',
    case when v_had_override then v_prev_override.search_term else v_prev_match.search_term end,v_term,
    v_prev_match.status,v_prev_match.best_code,v_prev_match.best_description,v_prev_match.current_value_cop,
    v_result_match.status,v_result_match.best_code,v_result_match.best_description,v_result_match.current_value_cop,v_note
  );

  return jsonb_build_object(
    'ok',true,'action','CONFIRM','search_term',v_term,'probe',v_probe,'matcher_result',v_match,
    'match_origin','MANUAL_SEARCH_TERM','interpretation','MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH'
  );
end;
$function$;
revoke all on function public.dashboard_set_fasecolda_search_term_override(text,text,text,text) from public,anon,authenticated;
grant execute on function public.dashboard_set_fasecolda_search_term_override(text,text,text,text) to service_role;

create or replace function public.invalidate_fasecolda_search_term_override_on_identity_change()
returns trigger
language plpgsql
security definer
set search_path to 'public','pg_catalog'
as $function$
declare
  v_prev public.lot_fasecolda_search_term_overrides%rowtype;
  v_match public.lot_fasecolda_matches%rowtype;
begin
  if old.title is distinct from new.title or old.brand is distinct from new.brand or old.line is distinct from new.line or old.model_year is distinct from new.model_year then
    select * into v_prev from public.lot_fasecolda_search_term_overrides where lot_id=new.id;
    if found then
      select * into v_match from public.lot_fasecolda_matches where lot_id=new.id;
      insert into public.lot_fasecolda_search_term_override_history(
        lot_id,external_lot_id,action,previous_search_term,new_search_term,
        previous_match_status,previous_best_code,previous_best_description,previous_value_cop,note
      ) values(
        new.id,new.external_lot_id,'INVALIDATE_IDENTITY_CHANGE',v_prev.search_term,null,
        v_match.status,v_match.best_code,v_match.best_description,v_match.current_value_cop,
        'Vehicle identity fields changed; manual search-term override and derived match invalidated.'
      );
      delete from public.lot_fasecolda_search_term_overrides where lot_id=new.id;
      delete from public.lot_fasecolda_candidates where lot_id=new.id;
      delete from public.lot_fasecolda_matches where lot_id=new.id;
    end if;
  end if;
  return new;
end;
$function$;
revoke all on function public.invalidate_fasecolda_search_term_override_on_identity_change() from public,anon,authenticated;
drop trigger if exists trg_invalidate_fasecolda_search_term_override on public.auction_lots;
create trigger trg_invalidate_fasecolda_search_term_override
after update of title,brand,line,model_year on public.auction_lots
for each row execute function public.invalidate_fasecolda_search_term_override_on_identity_change();

create or replace view public.lot_fasecolda_effective_current as
select
  fm.lot_id,
  case when mr.lot_id is not null then 'HIGH' else fm.status end as status,
  fm.search_term,
  case when mr.lot_id is not null then mr.chosen_code else fm.best_code end as best_code,
  case when mr.lot_id is not null then mr.chosen_description else fm.best_description end as best_description,
  case when mr.lot_id is not null then mr.candidate_score else fm.best_score end as best_score,
  fm.second_score,
  fm.candidate_count,
  case when mr.lot_id is not null then coalesce(mh.value_cop,mr.chosen_value_cop) else fm.current_value_cop end as current_value_cop,
  fm.candidate_min_cop,
  fm.candidate_median_cop,
  fm.candidate_max_cop,
  case when mr.lot_id is not null then mh.value_date else fm.latest_history_date end as latest_history_date,
  (case when mr.lot_id is not null then 1.0::numeric else fm.confidence end)::numeric(5,4) as confidence,
  case when mr.lot_id is not null then mr.resolved_at else fm.matched_at end as matched_at,
  case when mr.lot_id is not null then 'Manually confirmed from a public Fasecolda candidate; matcher result preserved separately.'
       when so.lot_id is not null then 'Matcher rerun with a human-confirmed Fasecolda search term; matcher status and scoring remain unchanged.'
       else fm.note end as note,
  case when mr.lot_id is not null then 'MANUAL_CONFIRMED'
       when so.lot_id is not null then 'MANUAL_SEARCH_TERM'
       else 'AUTOMATIC' end as match_origin,
  fm.status as automatic_status,
  fm.best_code as automatic_best_code,
  fm.best_description as automatic_best_description,
  fm.best_score as automatic_best_score,
  mr.resolved_at as manual_resolved_at,
  case when mr.lot_id is not null then 'MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH'
       when so.lot_id is not null then 'MANUAL_FASECOLDA_SEARCH_TERM_NOT_MATCH'
       else 'MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH' end as interpretation,
  case when so.lot_id is not null then 'MANUAL_SEARCH_TERM' else 'TITLE_DERIVED' end as search_term_origin,
  so.search_term as search_term_override,
  so.confirmed_at as search_term_overridden_at
from public.lot_fasecolda_matches fm
left join public.lot_fasecolda_manual_resolutions mr on mr.lot_id=fm.lot_id
left join public.lot_fasecolda_search_term_overrides so on so.lot_id=fm.lot_id
left join lateral (
  select h.value_date,h.value_cop from public.fasecolda_value_history h
  where mr.lot_id is not null and h.code=mr.chosen_code and h.model_year=mr.model_year
  order by h.value_date desc limit 1
) mh on true;
revoke all on public.lot_fasecolda_effective_current from public,anon,authenticated;
grant select on public.lot_fasecolda_effective_current to service_role;
