create table if not exists public.operational_alert_events(
  id bigint generated by default as identity primary key,
  lot_id bigint not null references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  alert_type text not null check(alert_type in ('CLOSING_2H','HIGH_PRESSURE','CLOSE_EXTENSION')),
  severity text not null check(severity in ('INFO','WARNING','URGENT')),
  dedupe_key text not null unique,
  triggered_at timestamptz not null default clock_timestamp(),
  source_observed_at timestamptz,
  title text,
  current_bid_cop numeric,
  closes_at timestamptz,
  review_state text,
  pressure_level text,
  operational_rank integer,
  preliminary_headroom_cop numeric,
  peritaje_count integer,
  message text not null,
  evidence jsonb not null default '{}'::jsonb,
  interpretation text not null default 'OPERATIONAL_ALERT_NOT_BUY_SIGNAL' check(interpretation='OPERATIONAL_ALERT_NOT_BUY_SIGNAL'),
  acknowledged_at timestamptz,
  acknowledged_note text
);

create index if not exists idx_operational_alert_events_triggered on public.operational_alert_events(triggered_at desc);
create index if not exists idx_operational_alert_events_lot on public.operational_alert_events(lot_id,triggered_at desc);
create index if not exists idx_operational_alert_events_open on public.operational_alert_events(triggered_at desc) where acknowledged_at is null;

alter table public.operational_alert_events enable row level security;
revoke all on public.operational_alert_events from public,anon,authenticated;
grant select,insert,update on public.operational_alert_events to service_role;

create or replace view public.lot_close_extension_events as
with ordered as (
  select
    s.id as snapshot_id,
    s.lot_id,
    s.observed_at,
    s.closes_at,
    lag(s.closes_at) over(partition by s.lot_id order by s.observed_at,s.id) as prev_closes_at
  from public.auction_snapshots s
  where s.closes_at is not null
)
select
  o.snapshot_id,
  o.lot_id,
  l.external_lot_id,
  o.observed_at,
  o.prev_closes_at,
  o.closes_at as new_closes_at,
  round(extract(epoch from (o.closes_at-o.prev_closes_at))/60.0,1) as extension_minutes
from ordered o
join public.auction_lots l on l.id=o.lot_id
where o.prev_closes_at is not null
  and o.closes_at>o.prev_closes_at;

revoke all on public.lot_close_extension_events from public,anon,authenticated;
grant select on public.lot_close_extension_events to service_role;

create or replace function public.refresh_operational_alerts()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_closing integer:=0;
  v_pressure integer:=0;
  v_extensions integer:=0;
begin
  insert into public.operational_alert_events(
    lot_id,external_lot_id,alert_type,severity,dedupe_key,source_observed_at,title,current_bid_cop,closes_at,
    review_state,pressure_level,operational_rank,preliminary_headroom_cop,peritaje_count,message,evidence
  )
  select
    q.lot_id,q.external_lot_id,'CLOSING_2H','URGENT',
    'CLOSING_2H:'||q.external_lot_id||':'||to_char(q.closes_at at time zone 'UTC','YYYYMMDDHH24MISS'),
    clock_timestamp(),q.title,q.current_bid_cop,q.closes_at,q.review_state,q.pressure_level,q.operational_rank,
    q.preliminary_headroom_before_fixed_costs_cop,q.peritaje_count,
    'REVIEW_NOW con cierre dentro de 2 horas',
    jsonb_build_object('closing_bucket',q.closing_bucket,'hours_to_close',q.hours_to_close,'review_score',q.review_score)
  from public.dashboard_operational_queue q
  where q.review_state='REVIEW_NOW'
    and q.closes_at>clock_timestamp()
    and q.closes_at<=clock_timestamp()+interval '2 hours'
  on conflict(dedupe_key) do nothing;
  get diagnostics v_closing=row_count;

  insert into public.operational_alert_events(
    lot_id,external_lot_id,alert_type,severity,dedupe_key,source_observed_at,title,current_bid_cop,closes_at,
    review_state,pressure_level,operational_rank,preliminary_headroom_cop,peritaje_count,message,evidence
  )
  select
    q.lot_id,q.external_lot_id,'HIGH_PRESSURE','WARNING',
    'HIGH_PRESSURE:'||q.external_lot_id||':'||to_char(date_trunc('hour',q.pressure_last_change_at) at time zone 'UTC','YYYYMMDDHH24'),
    q.pressure_last_change_at,q.title,q.current_bid_cop,q.closes_at,q.review_state,q.pressure_level,q.operational_rank,
    q.preliminary_headroom_before_fixed_costs_cop,q.peritaje_count,
    'Presión competitiva HIGH observada',
    jsonb_build_object('changes_2h',q.pressure_changes_2h,'bid_up_2h',q.pressure_bid_up_2h,'price_up_2h_cop',q.pressure_price_up_2h_cop,'review_score',q.review_score)
  from public.dashboard_operational_queue q
  where q.review_state in ('REVIEW_NOW','REVIEW_SOON')
    and q.pressure_level='HIGH'
    and q.pressure_last_change_at is not null
    and q.pressure_last_change_at>=clock_timestamp()-interval '2 hours'
  on conflict(dedupe_key) do nothing;
  get diagnostics v_pressure=row_count;

  insert into public.operational_alert_events(
    lot_id,external_lot_id,alert_type,severity,dedupe_key,source_observed_at,title,current_bid_cop,closes_at,
    review_state,pressure_level,operational_rank,preliminary_headroom_cop,peritaje_count,message,evidence
  )
  select
    x.lot_id,x.external_lot_id,'CLOSE_EXTENSION','INFO','CLOSE_EXTENSION:'||x.snapshot_id,
    x.observed_at,q.title,q.current_bid_cop,x.new_closes_at,q.review_state,q.pressure_level,q.operational_rank,
    q.preliminary_headroom_before_fixed_costs_cop,q.peritaje_count,
    'Cierre de subasta extendido en '||x.extension_minutes||' minutos',
    jsonb_build_object('previous_closes_at',x.prev_closes_at,'new_closes_at',x.new_closes_at,'extension_minutes',x.extension_minutes)
  from public.lot_close_extension_events x
  join public.dashboard_operational_queue q on q.lot_id=x.lot_id
  where x.observed_at>=clock_timestamp()-interval '7 days'
  on conflict(dedupe_key) do nothing;
  get diagnostics v_extensions=row_count;

  return jsonb_build_object(
    'closing_2h_inserted',v_closing,
    'high_pressure_inserted',v_pressure,
    'close_extensions_inserted',v_extensions,
    'interpretation','OPERATIONAL_ALERT_NOT_BUY_SIGNAL'
  );
end;
$$;

revoke all on function public.refresh_operational_alerts() from public,anon,authenticated;
grant execute on function public.refresh_operational_alerts() to service_role;

create or replace view public.dashboard_operational_alert_feed as
select
  e.id,e.external_lot_id,e.alert_type,e.severity,e.triggered_at,e.source_observed_at,e.title,e.current_bid_cop,e.closes_at,
  e.review_state,e.pressure_level,e.operational_rank,e.preliminary_headroom_cop,e.peritaje_count,e.message,e.evidence,
  e.interpretation,e.acknowledged_at,e.acknowledged_note,
  (e.acknowledged_at is null) as is_open
from public.operational_alert_events e;

revoke all on public.dashboard_operational_alert_feed from public,anon,authenticated;
grant select on public.dashboard_operational_alert_feed to service_role;

do $$
begin
  if exists(select 1 from cron.job where jobname='superbid-operational-alerts-v27') then
    perform cron.unschedule('superbid-operational-alerts-v27');
  end if;
end $$;

select cron.schedule('superbid-operational-alerts-v27','* * * * *','select public.refresh_operational_alerts();');
