create table if not exists public.fasecolda_year_reference_evidence_state(
  logical_key text primary key check(logical_key ~ '^[0-9a-f]{32}$'),
  current_case_key text check(current_case_key is null or current_case_key ~ '^[0-9a-f]{32}$'),
  previous_case_key text check(previous_case_key is null or previous_case_key ~ '^[0-9a-f]{32}$'),
  stored_brand text,
  term_brand text,
  line_term text,
  model_year integer,
  current_reason text,
  last_event_type text not null check(last_event_type in ('NEW','UNCHANGED','CHANGED','RESOLVED','REOPENED')),
  current_lot_count integer not null default 0 check(current_lot_count>=0),
  source_import_marker timestamptz,
  first_seen_at timestamptz not null default clock_timestamp(),
  last_seen_at timestamptz,
  evidence_changed_at timestamptz,
  resolved_at timestamptz,
  last_refresh_at timestamptz not null default clock_timestamp()
);

create table if not exists public.fasecolda_year_reference_evidence_events(
  id bigint generated by default as identity primary key,
  logical_key text not null check(logical_key ~ '^[0-9a-f]{32}$'),
  event_type text not null check(event_type in ('NEW','UNCHANGED','CHANGED','RESOLVED','REOPENED')),
  previous_case_key text,
  case_key text,
  previous_reason text,
  current_reason text,
  lot_count integer,
  source_import_marker timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'FASECOLDA_YEAR_EVIDENCE_CHANGE_NOT_VALUATION' check(interpretation='FASECOLDA_YEAR_EVIDENCE_CHANGE_NOT_VALUATION')
);

alter table public.fasecolda_year_reference_evidence_state enable row level security;
alter table public.fasecolda_year_reference_evidence_events enable row level security;
revoke all on public.fasecolda_year_reference_evidence_state from public,anon,authenticated;
revoke all on public.fasecolda_year_reference_evidence_events from public,anon,authenticated;
grant select,insert,update,delete on public.fasecolda_year_reference_evidence_state to service_role;
grant select,insert on public.fasecolda_year_reference_evidence_events to service_role;
grant usage,select on sequence public.fasecolda_year_reference_evidence_events_id_seq to service_role;

create or replace function public.refresh_fasecolda_year_reference_evidence_v41()
returns jsonb
language plpgsql security definer set search_path=public,pg_catalog as $$
declare
  current_rec record;
  state_rec record;
  v_logical_key text;
  v_source_marker timestamptz;
  v_now timestamptz:=clock_timestamp();
  v_new integer:=0;
  v_unchanged integer:=0;
  v_changed integer:=0;
  v_resolved integer:=0;
  v_reopened integer:=0;
begin
  select max(imported_at) into v_source_marker from public.fasecolda_values;

  for current_rec in select * from public.dashboard_fasecolda_year_reference_case_queue loop
    v_logical_key:=md5(concat_ws('|',upper(coalesce(current_rec.stored_brand,'')),upper(coalesce(current_rec.term_brand,'')),upper(coalesce(current_rec.line_term,'')),coalesce(current_rec.model_year::text,'')));
    select * into state_rec from public.fasecolda_year_reference_evidence_state where logical_key=v_logical_key for update;

    if state_rec.logical_key is null then
      insert into public.fasecolda_year_reference_evidence_state(
        logical_key,current_case_key,stored_brand,term_brand,line_term,model_year,current_reason,last_event_type,current_lot_count,source_import_marker,first_seen_at,last_seen_at,evidence_changed_at,last_refresh_at
      ) values(
        v_logical_key,current_rec.case_key,current_rec.stored_brand,current_rec.term_brand,current_rec.line_term,current_rec.model_year,current_rec.year_reference_reason,'NEW',current_rec.lot_count,v_source_marker,v_now,v_now,v_now,v_now
      );
      insert into public.fasecolda_year_reference_evidence_events(logical_key,event_type,case_key,current_reason,lot_count,source_import_marker)
      values(v_logical_key,'NEW',current_rec.case_key,current_rec.year_reference_reason,current_rec.lot_count,v_source_marker);
      v_new:=v_new+1;

    elsif state_rec.last_event_type='RESOLVED' then
      insert into public.fasecolda_year_reference_evidence_events(logical_key,event_type,previous_case_key,case_key,previous_reason,current_reason,lot_count,source_import_marker)
      values(v_logical_key,'REOPENED',state_rec.previous_case_key,current_rec.case_key,state_rec.current_reason,current_rec.year_reference_reason,current_rec.lot_count,v_source_marker);
      update public.fasecolda_year_reference_evidence_state set
        current_case_key=current_rec.case_key,
        stored_brand=current_rec.stored_brand,term_brand=current_rec.term_brand,line_term=current_rec.line_term,model_year=current_rec.model_year,
        current_reason=current_rec.year_reference_reason,last_event_type='REOPENED',current_lot_count=current_rec.lot_count,
        source_import_marker=v_source_marker,last_seen_at=v_now,evidence_changed_at=v_now,resolved_at=null,last_refresh_at=v_now
      where logical_key=v_logical_key;
      v_reopened:=v_reopened+1;

    elsif state_rec.current_case_key is distinct from current_rec.case_key then
      insert into public.fasecolda_year_reference_evidence_events(logical_key,event_type,previous_case_key,case_key,previous_reason,current_reason,lot_count,source_import_marker)
      values(v_logical_key,'CHANGED',state_rec.current_case_key,current_rec.case_key,state_rec.current_reason,current_rec.year_reference_reason,current_rec.lot_count,v_source_marker);
      update public.fasecolda_year_reference_evidence_state set
        previous_case_key=state_rec.current_case_key,current_case_key=current_rec.case_key,
        stored_brand=current_rec.stored_brand,term_brand=current_rec.term_brand,line_term=current_rec.line_term,model_year=current_rec.model_year,
        current_reason=current_rec.year_reference_reason,last_event_type='CHANGED',current_lot_count=current_rec.lot_count,
        source_import_marker=v_source_marker,last_seen_at=v_now,evidence_changed_at=v_now,resolved_at=null,last_refresh_at=v_now
      where logical_key=v_logical_key;
      v_changed:=v_changed+1;

    elsif state_rec.source_import_marker is distinct from v_source_marker then
      insert into public.fasecolda_year_reference_evidence_events(logical_key,event_type,previous_case_key,case_key,previous_reason,current_reason,lot_count,source_import_marker)
      values(v_logical_key,'UNCHANGED',state_rec.previous_case_key,current_rec.case_key,state_rec.current_reason,current_rec.year_reference_reason,current_rec.lot_count,v_source_marker);
      update public.fasecolda_year_reference_evidence_state set
        current_reason=current_rec.year_reference_reason,last_event_type='UNCHANGED',current_lot_count=current_rec.lot_count,
        source_import_marker=v_source_marker,last_seen_at=v_now,resolved_at=null,last_refresh_at=v_now
      where logical_key=v_logical_key;
      v_unchanged:=v_unchanged+1;
    else
      update public.fasecolda_year_reference_evidence_state set
        current_lot_count=current_rec.lot_count,last_seen_at=v_now,last_refresh_at=v_now
      where logical_key=v_logical_key;
    end if;
  end loop;

  for state_rec in
    select st.* from public.fasecolda_year_reference_evidence_state st
    where st.last_event_type<>'RESOLVED'
      and not exists(
        select 1 from public.dashboard_fasecolda_year_reference_case_queue current_q
        where md5(concat_ws('|',upper(coalesce(current_q.stored_brand,'')),upper(coalesce(current_q.term_brand,'')),upper(coalesce(current_q.line_term,'')),coalesce(current_q.model_year::text,'')))=st.logical_key
      )
    for update
  loop
    insert into public.fasecolda_year_reference_evidence_events(logical_key,event_type,previous_case_key,previous_reason,lot_count,source_import_marker)
    values(state_rec.logical_key,'RESOLVED',state_rec.current_case_key,state_rec.current_reason,0,v_source_marker);
    update public.fasecolda_year_reference_evidence_state set
      previous_case_key=current_case_key,current_case_key=null,last_event_type='RESOLVED',current_lot_count=0,
      source_import_marker=v_source_marker,resolved_at=v_now,evidence_changed_at=v_now,last_refresh_at=v_now
    where logical_key=state_rec.logical_key;
    v_resolved:=v_resolved+1;
  end loop;

  return jsonb_build_object(
    'ok',true,'new',v_new,'unchanged_after_source_change',v_unchanged,'changed',v_changed,'resolved',v_resolved,'reopened',v_reopened,
    'source_import_marker',v_source_marker,'interpretation','FASECOLDA_YEAR_EVIDENCE_CHANGE_NOT_VALUATION'
  );
end$$;

revoke all on function public.refresh_fasecolda_year_reference_evidence_v41() from public,anon,authenticated;
grant execute on function public.refresh_fasecolda_year_reference_evidence_v41() to service_role;

create or replace view public.dashboard_fasecolda_year_reference_evidence_lifecycle as
select
  case_q.*,
  md5(concat_ws('|',upper(coalesce(case_q.stored_brand,'')),upper(coalesce(case_q.term_brand,'')),upper(coalesce(case_q.line_term,'')),coalesce(case_q.model_year::text,''))) as logical_key,
  st.previous_case_key,
  st.last_event_type as evidence_event_type,
  st.first_seen_at as evidence_first_seen_at,
  st.last_seen_at as evidence_last_seen_at,
  st.evidence_changed_at,
  st.source_import_marker,
  case
    when case_q.disposition_action is not null then 'DISPOSITION_CURRENT'
    when st.last_event_type in ('NEW','CHANGED','REOPENED') then 'REVIEW_REQUIRED'
    else 'OPEN_REVIEW'
  end as evidence_review_status,
  case
    when case_q.disposition_action='CONFIRM_COVERAGE_GAP' then 'NO_REVIEW_UNTIL_EVIDENCE_CHANGES'
    when case_q.disposition_action is not null then case_q.operational_next_action
    when st.last_event_type in ('NEW','CHANGED','REOPENED') then 'REVIEW_CHANGED_EVIDENCE'
    else case_q.operational_next_action
  end as lifecycle_next_action,
  'FASECOLDA_YEAR_EVIDENCE_CHANGE_NOT_VALUATION'::text as lifecycle_interpretation
from public.dashboard_fasecolda_year_reference_case_queue case_q
left join public.fasecolda_year_reference_evidence_state st
  on st.logical_key=md5(concat_ws('|',upper(coalesce(case_q.stored_brand,'')),upper(coalesce(case_q.term_brand,'')),upper(coalesce(case_q.line_term,'')),coalesce(case_q.model_year::text,'')));

revoke all on public.dashboard_fasecolda_year_reference_evidence_lifecycle from public,anon,authenticated;
grant select on public.dashboard_fasecolda_year_reference_evidence_lifecycle to service_role;

create or replace view public.dashboard_fasecolda_year_reference_evidence_events as
select e.* from public.fasecolda_year_reference_evidence_events e order by e.created_at desc,e.id desc;
revoke all on public.dashboard_fasecolda_year_reference_evidence_events from public,anon,authenticated;
grant select on public.dashboard_fasecolda_year_reference_evidence_events to service_role;

select public.refresh_fasecolda_year_reference_evidence_v41();

do $$
begin
  if exists(select 1 from cron.job where jobname='fasecolda-year-evidence-v41') then
    perform cron.unschedule('fasecolda-year-evidence-v41');
  end if;
end$$;
select cron.schedule('fasecolda-year-evidence-v41','*/30 * * * *','select public.refresh_fasecolda_year_reference_evidence_v41();');

comment on table public.fasecolda_year_reference_evidence_state is 'Lifecycle state for stable logical Fasecolda year-reference cases. Fingerprint changes trigger review; no valuation is produced.';
comment on function public.refresh_fasecolda_year_reference_evidence_v41() is 'Detects new, changed, unchanged-after-source-import, resolved and reopened year-reference evidence. Never writes match or valuation fields.';
