create table if not exists public.fasecolda_year_reference_case_dispositions(
  case_key text primary key,
  stored_brand text,
  term_brand text,
  line_term text,
  model_year integer,
  year_reference_reason text not null,
  available_years integer[],
  disposition_action text not null check(disposition_action in ('CONFIRM_COVERAGE_GAP','REQUEST_SOURCE_REFRESH','REFER_IDENTITY_REVIEW','REQUEST_MATCHER_RECHECK')),
  note text check(note is null or char_length(note)<=2000),
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  check(case_key ~ '^[0-9a-f]{32}$')
);

create table if not exists public.fasecolda_year_reference_case_disposition_history(
  id bigint generated by default as identity primary key,
  case_key text not null,
  action text not null check(action in ('CONFIRM_COVERAGE_GAP','REQUEST_SOURCE_REFRESH','REFER_IDENTITY_REVIEW','REQUEST_MATCHER_RECHECK','CLEAR')),
  year_reference_reason text,
  model_year integer,
  available_years integer[],
  note text check(note is null or char_length(note)<=2000),
  created_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'FASECOLDA_YEAR_GAP_DISPOSITION_NOT_VALUATION' check(interpretation='FASECOLDA_YEAR_GAP_DISPOSITION_NOT_VALUATION')
);

alter table public.fasecolda_year_reference_case_dispositions enable row level security;
alter table public.fasecolda_year_reference_case_disposition_history enable row level security;
revoke all on public.fasecolda_year_reference_case_dispositions from public,anon,authenticated;
revoke all on public.fasecolda_year_reference_case_disposition_history from public,anon,authenticated;
grant select,insert,update,delete on public.fasecolda_year_reference_case_dispositions to service_role;
grant select,insert on public.fasecolda_year_reference_case_disposition_history to service_role;
grant usage,select on sequence public.fasecolda_year_reference_case_disposition_history_id_seq to service_role;

create or replace view public.dashboard_fasecolda_year_reference_case_queue as
with x as (
  select d.*,
    md5(concat_ws('|',
      upper(coalesce(d.stored_brand,'')),upper(coalesce(d.term_brand,'')),upper(coalesce(d.line_term,'')),coalesce(d.model_year::text,''),d.year_reference_reason,
      coalesce(array_to_string(d.available_years,','),''),coalesce(d.nearest_lower_year::text,''),coalesce(d.nearest_lower_min_value_cop::text,''),coalesce(d.nearest_lower_max_value_cop::text,''),coalesce(array_to_string(d.nearest_lower_codes,','),''),
      coalesce(d.nearest_upper_year::text,''),coalesce(d.nearest_upper_min_value_cop::text,''),coalesce(d.nearest_upper_max_value_cop::text,''),coalesce(array_to_string(d.nearest_upper_codes,','),''))) as case_key
  from public.dashboard_fasecolda_year_reference_diagnostics d
), g as (
  select
    case_key,stored_brand,term_brand,line_term,model_year,year_reference_reason,available_years,
    nearest_lower_year,lower_year_distance,nearest_lower_min_value_cop,nearest_lower_max_value_cop,nearest_lower_codes,
    nearest_upper_year,upper_year_distance,nearest_upper_min_value_cop,nearest_upper_max_value_cop,nearest_upper_codes,
    max(evidence_imported_at) as evidence_imported_at,
    count(*) as lot_count,
    array_agg(external_lot_id order by external_lot_id) as external_lot_ids,
    max(review_score) as max_review_score,
    min(diagnostic_rank) as diagnostic_rank,
    min(next_action) as diagnostic_next_action
  from x
  group by case_key,stored_brand,term_brand,line_term,model_year,year_reference_reason,available_years,
    nearest_lower_year,lower_year_distance,nearest_lower_min_value_cop,nearest_lower_max_value_cop,nearest_lower_codes,
    nearest_upper_year,upper_year_distance,nearest_upper_min_value_cop,nearest_upper_max_value_cop,nearest_upper_codes
)
select g.*,
  d.disposition_action,
  d.note as disposition_note,
  d.updated_at as disposition_updated_at,
  case
    when d.disposition_action='CONFIRM_COVERAGE_GAP' then 'ACKNOWLEDGED_GAP'
    when d.disposition_action is not null then 'ACTION_REQUESTED'
    else 'OPEN'
  end as operational_status,
  case
    when d.disposition_action='CONFIRM_COVERAGE_GAP' then 'NO_FURTHER_FASECOLDA_ACTION_UNTIL_EVIDENCE_CHANGES'
    when d.disposition_action='REQUEST_SOURCE_REFRESH' then 'REFRESH_FASECOLDA_SOURCE'
    when d.disposition_action='REFER_IDENTITY_REVIEW' then 'REVIEW_IDENTITY'
    when d.disposition_action='REQUEST_MATCHER_RECHECK' then 'RECHECK_MATCHER'
    else g.diagnostic_next_action
  end as operational_next_action,
  'FASECOLDA_YEAR_GAP_DISPOSITION_NOT_VALUATION'::text as interpretation
from g
left join public.fasecolda_year_reference_case_dispositions d using(case_key);

revoke all on public.dashboard_fasecolda_year_reference_case_queue from public,anon,authenticated;
grant select on public.dashboard_fasecolda_year_reference_case_queue to service_role;

create or replace view public.dashboard_fasecolda_year_reference_lot_status as
with x as (
  select d.*,
    md5(concat_ws('|',
      upper(coalesce(d.stored_brand,'')),upper(coalesce(d.term_brand,'')),upper(coalesce(d.line_term,'')),coalesce(d.model_year::text,''),d.year_reference_reason,
      coalesce(array_to_string(d.available_years,','),''),coalesce(d.nearest_lower_year::text,''),coalesce(d.nearest_lower_min_value_cop::text,''),coalesce(d.nearest_lower_max_value_cop::text,''),coalesce(array_to_string(d.nearest_lower_codes,','),''),
      coalesce(d.nearest_upper_year::text,''),coalesce(d.nearest_upper_min_value_cop::text,''),coalesce(d.nearest_upper_max_value_cop::text,''),coalesce(array_to_string(d.nearest_upper_codes,','),''))) as case_key
  from public.dashboard_fasecolda_year_reference_diagnostics d
)
select x.*,q.disposition_action,q.operational_status,q.operational_next_action,
  'FASECOLDA_YEAR_GAP_DISPOSITION_NOT_VALUATION'::text as disposition_interpretation
from x
left join public.dashboard_fasecolda_year_reference_case_queue q using(case_key);

revoke all on public.dashboard_fasecolda_year_reference_lot_status from public,anon,authenticated;
grant select on public.dashboard_fasecolda_year_reference_lot_status to service_role;

create or replace function public.dashboard_set_fasecolda_year_reference_case_disposition(
  p_case_key text,p_action text,p_note text default null
) returns jsonb
language plpgsql security definer set search_path=public,pg_catalog as $$
declare
  v_case record;
  v_action text:=upper(trim(coalesce(p_action,'')));
  v_note text:=nullif(trim(coalesce(p_note,'')),'');
begin
  if p_case_key is null or p_case_key !~ '^[0-9a-f]{32}$' then raise exception 'invalid case key'; end if;
  if v_action not in ('CONFIRM_COVERAGE_GAP','REQUEST_SOURCE_REFRESH','REFER_IDENTITY_REVIEW','REQUEST_MATCHER_RECHECK','CLEAR') then raise exception 'invalid disposition action'; end if;
  if v_note is not null and char_length(v_note)>2000 then raise exception 'note too long'; end if;

  select * into v_case from public.dashboard_fasecolda_year_reference_case_queue where case_key=p_case_key;
  if v_case.case_key is null then raise exception 'current year-reference case not found'; end if;

  if v_action='CONFIRM_COVERAGE_GAP' and v_case.year_reference_reason not in ('YEAR_GAP_BETWEEN_REFERENCES','ONLY_OLDER_REFERENCES','ONLY_NEWER_REFERENCES','LINE_NOT_PRESENT_IN_IMPORTED_VALUES','REFERENCE_YEARS_UNAVAILABLE') then
    raise exception 'coverage gap confirmation incompatible with diagnostic';
  end if;
  if v_action='REFER_IDENTITY_REVIEW' and v_case.year_reference_reason<>'STORED_BRAND_DIFFERS_FROM_SEARCH_TERM' then
    raise exception 'identity review referral incompatible with diagnostic';
  end if;
  if v_action='REQUEST_MATCHER_RECHECK' and v_case.year_reference_reason<>'SAME_YEAR_REFERENCE_EXISTS_DIAGNOSTIC_STALE' then
    raise exception 'matcher recheck incompatible with diagnostic';
  end if;

  if v_action='CLEAR' then
    delete from public.fasecolda_year_reference_case_dispositions where case_key=p_case_key;
  else
    insert into public.fasecolda_year_reference_case_dispositions(case_key,stored_brand,term_brand,line_term,model_year,year_reference_reason,available_years,disposition_action,note,updated_at)
    values(v_case.case_key,v_case.stored_brand,v_case.term_brand,v_case.line_term,v_case.model_year,v_case.year_reference_reason,v_case.available_years,v_action,v_note,clock_timestamp())
    on conflict(case_key) do update set disposition_action=excluded.disposition_action,note=excluded.note,updated_at=clock_timestamp();
  end if;

  insert into public.fasecolda_year_reference_case_disposition_history(case_key,action,year_reference_reason,model_year,available_years,note)
  values(p_case_key,v_action,v_case.year_reference_reason,v_case.model_year,v_case.available_years,v_note);

  return jsonb_build_object('ok',true,'case_key',p_case_key,'action',v_action,'lot_count',v_case.lot_count,'interpretation','FASECOLDA_YEAR_GAP_DISPOSITION_NOT_VALUATION');
end$$;

revoke all on function public.dashboard_set_fasecolda_year_reference_case_disposition(text,text,text) from public,anon,authenticated;
grant execute on function public.dashboard_set_fasecolda_year_reference_case_disposition(text,text,text) to service_role;

comment on view public.dashboard_fasecolda_year_reference_case_queue is 'Groups identical year-reference evidence fingerprints across lots so one human disposition can cover repeated cases. Disposition never creates a valuation.';
comment on function public.dashboard_set_fasecolda_year_reference_case_disposition(text,text,text) is 'Records human operational disposition of a Fasecolda year-reference diagnostic. It never interpolates or writes valuation/match fields.';
