create table if not exists public.lot_fasecolda_manual_resolutions (
  lot_id bigint primary key references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  chosen_code text not null references public.fasecolda_references(code),
  model_year integer not null,
  chosen_description text not null,
  chosen_value_cop bigint not null check (chosen_value_cop > 0),
  candidate_score numeric,
  candidate_rank integer,
  source_evaluated_at timestamptz,
  note text check (note is null or char_length(note) <= 2000),
  resolved_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH',
  constraint lot_fasecolda_manual_resolutions_interpretation_check
    check (interpretation='MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH')
);

create table if not exists public.lot_fasecolda_manual_resolution_history (
  id bigint generated by default as identity primary key,
  lot_id bigint not null references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  action text not null check (action in ('CONFIRM','CLEAR','INVALIDATE_IDENTITY_CHANGE')),
  previous_code text,
  previous_description text,
  previous_value_cop bigint,
  chosen_code text,
  chosen_description text,
  chosen_value_cop bigint,
  candidate_score numeric,
  candidate_rank integer,
  source_evaluated_at timestamptz,
  note text check (note is null or char_length(note) <= 2000),
  created_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH',
  constraint lot_fasecolda_manual_resolution_history_interpretation_check
    check (interpretation='MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH')
);

alter table public.lot_fasecolda_manual_resolutions enable row level security;
alter table public.lot_fasecolda_manual_resolution_history enable row level security;
revoke all on public.lot_fasecolda_manual_resolutions from public,anon,authenticated;
revoke all on public.lot_fasecolda_manual_resolution_history from public,anon,authenticated;
grant select,insert,update,delete on public.lot_fasecolda_manual_resolutions to service_role;
grant select,insert on public.lot_fasecolda_manual_resolution_history to service_role;

create index if not exists idx_fasecolda_manual_history_lot_created
  on public.lot_fasecolda_manual_resolution_history(lot_id,created_at desc);

create or replace function public.dashboard_set_fasecolda_manual_resolution(
  p_external_lot_id text,
  p_action text,
  p_code text default null,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public','extensions','pg_catalog'
as $function$
declare
  v_lot public.auction_lots%rowtype;
  v_auto public.lot_fasecolda_matches%rowtype;
  v_candidate public.lot_fasecolda_candidates%rowtype;
  v_prev public.lot_fasecolda_manual_resolutions%rowtype;
  v_had_prev boolean := false;
  v_action text := upper(trim(coalesce(p_action,'')));
  v_note text := nullif(trim(coalesce(p_note,'')),'');
begin
  if p_external_lot_id is null or p_external_lot_id !~ '^\d{5,12}$' then
    raise exception 'invalid external lot id';
  end if;
  if v_action not in ('CONFIRM','CLEAR') then
    raise exception 'invalid manual resolution action';
  end if;
  if v_note is not null and char_length(v_note)>2000 then
    raise exception 'note too long';
  end if;

  select * into v_lot
  from public.auction_lots
  where external_lot_id=p_external_lot_id
  order by id desc limit 1;
  if not found then raise exception 'lot not found'; end if;

  select * into v_auto from public.lot_fasecolda_matches where lot_id=v_lot.id;
  select * into v_prev from public.lot_fasecolda_manual_resolutions where lot_id=v_lot.id;
  v_had_prev := found;

  if v_action='CLEAR' then
    if not v_had_prev then raise exception 'manual resolution not found'; end if;
    insert into public.lot_fasecolda_manual_resolution_history(
      lot_id,external_lot_id,action,previous_code,previous_description,previous_value_cop,note
    ) values(
      v_lot.id,v_lot.external_lot_id,'CLEAR',v_prev.chosen_code,v_prev.chosen_description,v_prev.chosen_value_cop,v_note
    );
    delete from public.lot_fasecolda_manual_resolutions where lot_id=v_lot.id;
    return jsonb_build_object(
      'ok',true,'external_lot_id',v_lot.external_lot_id,'action','CLEAR',
      'effective_status',v_auto.status,'match_origin','AUTOMATIC',
      'interpretation','MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH'
    );
  end if;

  if p_code is null or trim(p_code)='' then raise exception 'candidate code required'; end if;
  if v_auto.lot_id is null then raise exception 'automatic Fasecolda match not found'; end if;
  if v_auto.status not in ('AMBIGUOUS','MEDIUM') and not v_had_prev then
    raise exception 'manual resolution is allowed only for AMBIGUOUS or MEDIUM automatic matches';
  end if;

  select * into v_candidate
  from public.lot_fasecolda_candidates
  where lot_id=v_lot.id and code=trim(p_code)
  limit 1;
  if not found then raise exception 'selected code is not a current candidate for this lot'; end if;
  if v_candidate.model_year is distinct from v_lot.model_year then
    raise exception 'candidate model year does not match lot';
  end if;
  if v_candidate.current_value_cop is null or v_candidate.current_value_cop<=0 then
    raise exception 'candidate has no usable current value';
  end if;
  if not exists(select 1 from public.fasecolda_references r where r.code=v_candidate.code) then
    raise exception 'candidate reference not found';
  end if;
  if not public.fasecolda_line_compatible(v_lot.title,v_lot.brand,v_candidate.description) then
    raise exception 'candidate fails Fasecolda identity guard';
  end if;

  insert into public.lot_fasecolda_manual_resolutions(
    lot_id,external_lot_id,chosen_code,model_year,chosen_description,chosen_value_cop,
    candidate_score,candidate_rank,source_evaluated_at,note,resolved_at,updated_at
  ) values(
    v_lot.id,v_lot.external_lot_id,v_candidate.code,v_candidate.model_year,v_candidate.description,
    v_candidate.current_value_cop,v_candidate.score,v_candidate.rank_no,v_candidate.evaluated_at,
    v_note,clock_timestamp(),clock_timestamp()
  )
  on conflict(lot_id) do update set
    external_lot_id=excluded.external_lot_id,
    chosen_code=excluded.chosen_code,
    model_year=excluded.model_year,
    chosen_description=excluded.chosen_description,
    chosen_value_cop=excluded.chosen_value_cop,
    candidate_score=excluded.candidate_score,
    candidate_rank=excluded.candidate_rank,
    source_evaluated_at=excluded.source_evaluated_at,
    note=excluded.note,
    resolved_at=excluded.resolved_at,
    updated_at=excluded.updated_at;

  insert into public.lot_fasecolda_manual_resolution_history(
    lot_id,external_lot_id,action,previous_code,previous_description,previous_value_cop,
    chosen_code,chosen_description,chosen_value_cop,candidate_score,candidate_rank,source_evaluated_at,note
  ) values(
    v_lot.id,v_lot.external_lot_id,'CONFIRM',
    case when v_had_prev then v_prev.chosen_code end,
    case when v_had_prev then v_prev.chosen_description end,
    case when v_had_prev then v_prev.chosen_value_cop end,
    v_candidate.code,v_candidate.description,v_candidate.current_value_cop,
    v_candidate.score,v_candidate.rank_no,v_candidate.evaluated_at,v_note
  );

  return jsonb_build_object(
    'ok',true,'external_lot_id',v_lot.external_lot_id,'action','CONFIRM',
    'chosen_code',v_candidate.code,'chosen_value_cop',v_candidate.current_value_cop,
    'effective_status','HIGH','match_origin','MANUAL_CONFIRMED',
    'automatic_status',v_auto.status,
    'interpretation','MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH'
  );
end;
$function$;

revoke all on function public.dashboard_set_fasecolda_manual_resolution(text,text,text,text) from public,anon,authenticated;
grant execute on function public.dashboard_set_fasecolda_manual_resolution(text,text,text,text) to service_role;

create or replace function public.invalidate_manual_fasecolda_resolution_on_identity_change()
returns trigger
language plpgsql
security definer
set search_path to 'public','pg_catalog'
as $function$
declare
  v_prev public.lot_fasecolda_manual_resolutions%rowtype;
begin
  if old.title is distinct from new.title
     or old.brand is distinct from new.brand
     or old.line is distinct from new.line
     or old.model_year is distinct from new.model_year then
    select * into v_prev from public.lot_fasecolda_manual_resolutions where lot_id=new.id;
    if found then
      insert into public.lot_fasecolda_manual_resolution_history(
        lot_id,external_lot_id,action,previous_code,previous_description,previous_value_cop,note
      ) values(
        new.id,new.external_lot_id,'INVALIDATE_IDENTITY_CHANGE',
        v_prev.chosen_code,v_prev.chosen_description,v_prev.chosen_value_cop,
        'Vehicle identity fields changed; manual Fasecolda resolution invalidated automatically.'
      );
      delete from public.lot_fasecolda_manual_resolutions where lot_id=new.id;
    end if;
  end if;
  return new;
end;
$function$;

revoke all on function public.invalidate_manual_fasecolda_resolution_on_identity_change() from public,anon,authenticated;

drop trigger if exists trg_invalidate_manual_fasecolda_resolution on public.auction_lots;
create trigger trg_invalidate_manual_fasecolda_resolution
after update of title,brand,line,model_year on public.auction_lots
for each row execute function public.invalidate_manual_fasecolda_resolution_on_identity_change();

create or replace view public.lot_fasecolda_effective_current as
select
  fm.lot_id,
  case when mr.lot_id is not null then 'HIGH' else fm.status end as status,
  fm.search_term,
  case when mr.lot_id is not null then mr.chosen_code else fm.best_code end as best_code,
  case when mr.lot_id is not null then mr.chosen_description else fm.best_description end as best_description,
  case when mr.lot_id is not null then mr.candidate_score else fm.best_score end as best_score,
  fm.second_score,
  fm.candidate_count,
  case when mr.lot_id is not null then coalesce(mh.value_cop,mr.chosen_value_cop) else fm.current_value_cop end as current_value_cop,
  fm.candidate_min_cop,
  fm.candidate_median_cop,
  fm.candidate_max_cop,
  case when mr.lot_id is not null then mh.value_date else fm.latest_history_date end as latest_history_date,
  (case when mr.lot_id is not null then 1.0::numeric else fm.confidence end)::numeric(5,4) as confidence,
  case when mr.lot_id is not null then mr.resolved_at else fm.matched_at end as matched_at,
  case when mr.lot_id is not null
       then 'Manually confirmed from a public Fasecolda candidate; automatic match preserved separately.'
       else fm.note end as note,
  case when mr.lot_id is not null then 'MANUAL_CONFIRMED' else 'AUTOMATIC' end as match_origin,
  fm.status as automatic_status,
  fm.best_code as automatic_best_code,
  fm.best_description as automatic_best_description,
  fm.best_score as automatic_best_score,
  mr.resolved_at as manual_resolved_at,
  'MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH'::text as interpretation
from public.lot_fasecolda_matches fm
left join public.lot_fasecolda_manual_resolutions mr on mr.lot_id=fm.lot_id
left join lateral (
  select h.value_date,h.value_cop
  from public.fasecolda_value_history h
  where mr.lot_id is not null
    and h.code=mr.chosen_code
    and h.model_year=mr.model_year
  order by h.value_date desc
  limit 1
) mh on true;

revoke all on public.lot_fasecolda_effective_current from public,anon,authenticated;
grant select on public.lot_fasecolda_effective_current to service_role;

create or replace view public.lot_intelligence_current as
select
  l.id as lot_id,
  l.external_lot_id,
  l.title,
  l.brand,
  l.line,
  l.model_year,
  l.city,
  l.seller,
  l.url,
  l.initial_bid_cop,
  s.displayed_price_cop as current_bid_cop,
  s.bid_count,
  s.observed_at as bid_observed_at,
  q.closes_at,
  o.outcome,
  fm.status as fasecolda_status,
  fm.best_code as fasecolda_code,
  fm.best_description as fasecolda_description,
  fm.current_value_cop as fasecolda_current_cop,
  fm.candidate_min_cop as fasecolda_min_cop,
  fm.candidate_median_cop as fasecolda_median_cop,
  fm.candidate_max_cop as fasecolda_max_cop,
  fm.latest_history_date as fasecolda_latest_date,
  fm.confidence as fasecolda_confidence,
  h12.value_cop as fasecolda_12m_ago_cop,
  case when h12.value_cop>0 and fm.current_value_cop is not null
       then round(((fm.current_value_cop::numeric/h12.value_cop::numeric)-1)*100,2)
       else null::numeric end as fasecolda_change_12m_pct,
  coalesce(att.peritaje_count,0) as peritaje_count,
  coalesce(att.peritajes,'[]'::jsonb) as peritajes
from public.auction_lots l
left join public.auction_outcomes o on o.lot_id=l.id
left join public.collection_queue q on q.external_lot_id=l.external_lot_id
left join lateral (
  select ss.* from public.auction_snapshots ss
  where ss.lot_id=l.id order by ss.observed_at desc limit 1
) s on true
left join public.lot_fasecolda_effective_current fm on fm.lot_id=l.id
left join lateral (
  select vh.value_cop
  from public.fasecolda_value_history vh
  where vh.code=fm.best_code
    and vh.model_year=l.model_year
    and fm.latest_history_date is not null
    and vh.value_date <= (fm.latest_history_date - interval '11 months')
  order by vh.value_date desc limit 1
) h12 on true
left join lateral (
  select count(*)::integer as peritaje_count,
         jsonb_agg(jsonb_build_object('name',a.name,'url',a.url,'discovered_at',a.discovered_at) order by a.discovered_at desc) as peritajes
  from public.lot_attachments a
  where a.lot_id=l.id and a.kind='PERITAJE'
) att on true;

create or replace view public.dashboard_lot_current as
select
  r.lot_id,
  r.external_lot_id,
  r.title,
  r.brand,
  r.line,
  r.model_year,
  r.city,
  r.seller,
  r.url,
  r.initial_bid_cop,
  r.current_bid_cop,
  r.bid_count,
  r.bid_observed_at,
  r.closes_at,
  r.outcome,
  r.commission_percent_public,
  r.auction_id,
  r.auction_desc,
  r.fasecolda_status,
  r.fasecolda_code,
  r.fasecolda_description,
  r.fasecolda_current_cop,
  r.fasecolda_12m_ago_cop,
  r.fasecolda_change_12m_pct,
  r.fasecolda_confidence,
  r.preliminary_resale_cop,
  r.ceiling_before_fixed_costs_cop,
  r.preliminary_headroom_before_fixed_costs_cop,
  r.opportunity_state,
  r.peritaje_count,
  r.peritajes,
  r.review_score,
  r.review_state,
  r.review_reasons,
  r.hours_to_close,
  m.market_status,
  m.market_comparable_count_live,
  m.median_asking_cop,
  m.p25_asking_cop,
  m.p75_asking_cop,
  m.market_quick_sale_cop,
  m.market_dispersion_pct,
  m.market_confidence,
  m.market_validation_available,
  m.costs_complete,
  m.cost_reviewed_at,
  m.fixed_costs_market_cop,
  m.conservative_resale_market_validated_cop,
  m.max_bid_market_validated_cop,
  m.market_headroom_cop,
  m.expected_profit_current_cop,
  m.expected_roi_current_pct,
  m.market_final_buy_recommendation_available,
  m.final_decision,
  fe.match_origin as fasecolda_match_origin,
  fe.automatic_status as fasecolda_automatic_status,
  fe.automatic_best_code as fasecolda_automatic_best_code,
  fe.manual_resolved_at as fasecolda_manual_resolved_at,
  fe.interpretation as fasecolda_match_interpretation
from public.lot_review_queue_current r
left join public.lot_opportunity_market_validated m on m.lot_id=r.lot_id
left join public.lot_fasecolda_effective_current fe on fe.lot_id=r.lot_id;

create or replace view public.dashboard_fasecolda_resolution_queue as
select
  d.external_lot_id,
  d.lot_id,
  d.title,
  d.brand,
  d.line,
  d.model_year,
  d.city,
  d.seller,
  d.current_bid_cop,
  d.closes_at,
  d.review_state,
  fm.status as automatic_status,
  fm.search_term,
  fm.best_code as automatic_best_code,
  fm.best_description as automatic_best_description,
  fm.best_score as automatic_best_score,
  fm.second_score as automatic_second_score,
  fm.candidate_count,
  case when mr.lot_id is null then 'UNRESOLVED' else 'RESOLVED' end as manual_resolution_status,
  mr.chosen_code,
  mr.chosen_description,
  mr.chosen_value_cop,
  mr.candidate_score as chosen_candidate_score,
  mr.candidate_rank as chosen_candidate_rank,
  mr.note as manual_note,
  mr.resolved_at,
  coalesce(ca.candidates,'[]'::jsonb) as candidates,
  'MANUAL_FASECOLDA_RESOLUTION_NOT_AUTOMATIC_MATCH'::text as interpretation
from public.dashboard_lot_current d
join public.lot_fasecolda_matches fm on fm.lot_id=d.lot_id
left join public.lot_fasecolda_manual_resolutions mr on mr.lot_id=d.lot_id
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'rank',c.rank_no,
      'code',c.code,
      'description',c.description,
      'score',c.score,
      'current_value_cop',c.current_value_cop,
      'model_year',c.model_year,
      'evaluated_at',c.evaluated_at
    ) order by c.rank_no,c.code
  ) as candidates
  from public.lot_fasecolda_candidates c
  where c.lot_id=d.lot_id
) ca on true
where fm.status in ('AMBIGUOUS','MEDIUM') or mr.lot_id is not null;

revoke all on public.dashboard_fasecolda_resolution_queue from public,anon,authenticated;
grant select on public.dashboard_fasecolda_resolution_queue to service_role;

comment on table public.lot_fasecolda_manual_resolutions is
'Current explicit human confirmation of one already-observed public Fasecolda candidate. Never an automatic match.';
comment on view public.lot_fasecolda_effective_current is
'Effective Fasecolda reference: manual confirmed candidate when present, otherwise preserved automatic matcher output. Origin is explicit.';
comment on view public.dashboard_fasecolda_resolution_queue is
'Backend-only queue for human resolution of AMBIGUOUS/MEDIUM Fasecolda candidates.';
