alter table public.operational_alert_events
  add column if not exists manual_disposition text,
  add column if not exists system_resolved_at timestamptz,
  add column if not exists system_resolution_reason text;

alter table public.operational_alert_events
  drop constraint if exists operational_alert_events_manual_disposition_check;
alter table public.operational_alert_events
  add constraint operational_alert_events_manual_disposition_check
  check(manual_disposition is null or manual_disposition in ('ACKNOWLEDGED','DISMISSED'));

create index if not exists idx_operational_alert_events_system_open
  on public.operational_alert_events(source_observed_at desc)
  where system_resolved_at is null;

create table if not exists public.operational_alert_action_history(
  id bigint generated by default as identity primary key,
  alert_id bigint not null references public.operational_alert_events(id) on delete cascade,
  external_lot_id text not null,
  action text not null check(action in ('ACKNOWLEDGE','DISMISS','REOPEN')),
  action_at timestamptz not null default clock_timestamp(),
  note text,
  previous_disposition text,
  new_disposition text,
  interpretation text not null default 'ALERT_LIFECYCLE_ACTION_NOT_BUY_SIGNAL'
    check(interpretation='ALERT_LIFECYCLE_ACTION_NOT_BUY_SIGNAL')
);

create index if not exists idx_operational_alert_action_history_alert
  on public.operational_alert_action_history(alert_id,action_at desc);

alter table public.operational_alert_action_history enable row level security;
revoke all on public.operational_alert_action_history from public,anon,authenticated;
grant select,insert on public.operational_alert_action_history to service_role;

create or replace function public.dashboard_set_operational_alert_disposition(
  p_alert_id bigint,
  p_action text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_action text:=upper(trim(coalesce(p_action,'')));
  v_note text:=nullif(trim(coalesce(p_note,'')),'');
  v_row public.operational_alert_events%rowtype;
  v_previous text;
  v_new text;
begin
  if v_action not in ('ACKNOWLEDGE','DISMISS','REOPEN') then
    raise exception 'invalid alert action';
  end if;
  if v_note is not null and length(v_note)>1000 then
    raise exception 'note too long';
  end if;

  select * into v_row
  from public.operational_alert_events
  where id=p_alert_id
  for update;
  if not found then
    raise exception 'alert not found';
  end if;

  v_previous:=v_row.manual_disposition;
  v_new:=case
    when v_action='ACKNOWLEDGE' then 'ACKNOWLEDGED'
    when v_action='DISMISS' then 'DISMISSED'
    else null
  end;

  update public.operational_alert_events
  set manual_disposition=v_new,
      acknowledged_at=case when v_action='REOPEN' then null else clock_timestamp() end,
      acknowledged_note=case when v_action='REOPEN' then null else v_note end
  where id=p_alert_id;

  insert into public.operational_alert_action_history(
    alert_id,external_lot_id,action,note,previous_disposition,new_disposition
  ) values(
    p_alert_id,v_row.external_lot_id,v_action,v_note,v_previous,v_new
  );

  return jsonb_build_object(
    'ok',true,
    'alert_id',p_alert_id,
    'action',v_action,
    'manual_disposition',v_new,
    'system_resolved_at',v_row.system_resolved_at,
    'interpretation','ALERT_LIFECYCLE_ACTION_NOT_BUY_SIGNAL'
  );
end;
$$;

revoke all on function public.dashboard_set_operational_alert_disposition(bigint,text,text) from public,anon,authenticated;
grant execute on function public.dashboard_set_operational_alert_disposition(bigint,text,text) to service_role;

create or replace function public.resolve_operational_alerts()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_closing integer:=0;
  v_pressure integer:=0;
  v_extension integer:=0;
begin
  update public.operational_alert_events e
  set system_resolved_at=clock_timestamp(),
      system_resolution_reason='CONDITION_NO_LONGER_ACTIVE'
  where e.alert_type='CLOSING_2H'
    and e.system_resolved_at is null
    and not exists(
      select 1
      from public.dashboard_operational_queue q
      where q.lot_id=e.lot_id
        and q.review_state='REVIEW_NOW'
        and q.closes_at>clock_timestamp()
        and q.closes_at<=clock_timestamp()+interval '2 hours'
    );
  get diagnostics v_closing=row_count;

  update public.operational_alert_events e
  set system_resolved_at=clock_timestamp(),
      system_resolution_reason='CONDITION_NO_LONGER_ACTIVE'
  where e.alert_type='HIGH_PRESSURE'
    and e.system_resolved_at is null
    and not exists(
      select 1
      from public.dashboard_operational_queue q
      where q.lot_id=e.lot_id
        and q.review_state in ('REVIEW_NOW','REVIEW_SOON')
        and q.pressure_level='HIGH'
        and q.pressure_last_change_at is not null
        and q.pressure_last_change_at>=clock_timestamp()-interval '2 hours'
    );
  get diagnostics v_pressure=row_count;

  update public.operational_alert_events e
  set system_resolved_at=clock_timestamp(),
      system_resolution_reason='EVENT_AGED_24H'
  where e.alert_type='CLOSE_EXTENSION'
    and e.system_resolved_at is null
    and coalesce(e.source_observed_at,e.triggered_at)<clock_timestamp()-interval '24 hours';
  get diagnostics v_extension=row_count;

  return jsonb_build_object(
    'closing_resolved',v_closing,
    'pressure_resolved',v_pressure,
    'extensions_resolved',v_extension,
    'interpretation','ALERT_LIFECYCLE_ACTION_NOT_BUY_SIGNAL'
  );
end;
$$;

revoke all on function public.resolve_operational_alerts() from public,anon,authenticated;
grant execute on function public.resolve_operational_alerts() to service_role;

create or replace function public.refresh_operational_alert_lifecycle()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_refresh jsonb;
  v_resolve jsonb;
begin
  v_refresh:=public.refresh_operational_alerts();
  v_resolve:=public.resolve_operational_alerts();
  return jsonb_build_object(
    'refresh',v_refresh,
    'resolve',v_resolve,
    'interpretation','ALERT_LIFECYCLE_ACTION_NOT_BUY_SIGNAL'
  );
end;
$$;

revoke all on function public.refresh_operational_alert_lifecycle() from public,anon,authenticated;
grant execute on function public.refresh_operational_alert_lifecycle() to service_role;

create or replace view public.dashboard_operational_alert_feed as
select
  e.id,e.external_lot_id,e.alert_type,e.severity,e.triggered_at,e.source_observed_at,e.title,e.current_bid_cop,e.closes_at,
  e.review_state,e.pressure_level,e.operational_rank,e.preliminary_headroom_cop,e.peritaje_count,e.message,e.evidence,
  e.interpretation,e.acknowledged_at,e.acknowledged_note,
  (e.acknowledged_at is null and e.system_resolved_at is null) as is_open,
  e.manual_disposition,e.system_resolved_at,e.system_resolution_reason,
  (e.acknowledged_at is null) as is_unattended,
  (e.system_resolved_at is null) as is_system_active
from public.operational_alert_events e;

revoke all on public.dashboard_operational_alert_feed from public,anon,authenticated;
grant select on public.dashboard_operational_alert_feed to service_role;

do $$
begin
  if exists(select 1 from cron.job where jobname='superbid-operational-alerts-v27') then
    perform cron.unschedule('superbid-operational-alerts-v27');
  end if;
  if exists(select 1 from cron.job where jobname='superbid-alert-lifecycle-v28') then
    perform cron.unschedule('superbid-alert-lifecycle-v28');
  end if;
end $$;

select cron.schedule(
  'superbid-alert-lifecycle-v28',
  '* * * * *',
  'select public.refresh_operational_alert_lifecycle();'
);
