create table if not exists public.lot_peritaje_reviews(
  id bigint generated by default as identity primary key,
  lot_id bigint not null unique references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  source_attachment_url text,
  mechanical_risk text,
  transmission_risk text,
  body_risk text,
  safety_risk text,
  electrical_risk text,
  tires_risk text,
  documentation_risk text,
  missing_parts_risk text,
  overall_risk text,
  repair_low_cop numeric,
  repair_base_cop numeric,
  repair_high_cop numeric,
  notes text,
  reviewed_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint lot_peritaje_reviews_notes_len check(notes is null or char_length(notes)<=5000),
  constraint lot_peritaje_reviews_repair_nonnegative check(coalesce(repair_low_cop,0)>=0 and coalesce(repair_base_cop,0)>=0 and coalesce(repair_high_cop,0)>=0),
  constraint lot_peritaje_reviews_repair_order check(repair_low_cop is null or repair_base_cop is null or repair_high_cop is null or (repair_low_cop<=repair_base_cop and repair_base_cop<=repair_high_cop))
);

create table if not exists public.lot_peritaje_review_history(
  id bigint generated by default as identity primary key,
  lot_id bigint not null references public.auction_lots(id) on delete cascade,
  external_lot_id text not null,
  source_attachment_url text,
  mechanical_risk text,
  transmission_risk text,
  body_risk text,
  safety_risk text,
  electrical_risk text,
  tires_risk text,
  documentation_risk text,
  missing_parts_risk text,
  overall_risk text,
  repair_low_cop numeric,
  repair_base_cop numeric,
  repair_high_cop numeric,
  notes text,
  marked_reviewed boolean not null default false,
  created_at timestamptz not null default clock_timestamp(),
  interpretation text not null default 'MANUAL_PERITAJE_REVIEW_NOT_AUTOMATED_DIAGNOSIS' check(interpretation='MANUAL_PERITAJE_REVIEW_NOT_AUTOMATED_DIAGNOSIS')
);

alter table public.lot_peritaje_reviews enable row level security;
alter table public.lot_peritaje_review_history enable row level security;
revoke all on public.lot_peritaje_reviews from public,anon,authenticated;
revoke all on public.lot_peritaje_review_history from public,anon,authenticated;
grant select,insert,update on public.lot_peritaje_reviews to service_role;
grant select,insert on public.lot_peritaje_review_history to service_role;

create or replace function public.dashboard_save_peritaje_review(
  p_external_lot_id text,
  p_source_attachment_url text default null,
  p_mechanical_risk text default null,
  p_transmission_risk text default null,
  p_body_risk text default null,
  p_safety_risk text default null,
  p_electrical_risk text default null,
  p_tires_risk text default null,
  p_documentation_risk text default null,
  p_missing_parts_risk text default null,
  p_repair_low_cop numeric default null,
  p_repair_base_cop numeric default null,
  p_repair_high_cop numeric default null,
  p_notes text default null,
  p_mark_reviewed boolean default false
) returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare
  v_lot_id bigint;
  v_allowed text[]:=array['LOW','MEDIUM','HIGH','CRITICAL','NOT_EVALUABLE'];
  v_values text[];
  v_score integer;
  v_overall text;
  v_reviewed_at timestamptz;
begin
  select id into v_lot_id from public.auction_lots where external_lot_id=p_external_lot_id limit 1;
  if v_lot_id is null then raise exception 'lot not found'; end if;
  if not exists(select 1 from public.lot_attachments where lot_id=v_lot_id and kind='PERITAJE') then raise exception 'public peritaje not available for lot'; end if;
  if p_source_attachment_url is not null and not exists(select 1 from public.lot_attachments where lot_id=v_lot_id and kind='PERITAJE' and url=p_source_attachment_url) then raise exception 'peritaje source url does not belong to lot'; end if;
  v_values:=array[nullif(upper(trim(p_mechanical_risk)),''),nullif(upper(trim(p_transmission_risk)),''),nullif(upper(trim(p_body_risk)),''),nullif(upper(trim(p_safety_risk)),''),nullif(upper(trim(p_electrical_risk)),''),nullif(upper(trim(p_tires_risk)),''),nullif(upper(trim(p_documentation_risk)),''),nullif(upper(trim(p_missing_parts_risk)),'')];
  if exists(select 1 from unnest(v_values) v where v is not null and not(v=any(v_allowed))) then raise exception 'invalid risk value'; end if;
  if p_notes is not null and char_length(p_notes)>5000 then raise exception 'notes too long'; end if;
  if coalesce(p_repair_low_cop,0)<0 or coalesce(p_repair_base_cop,0)<0 or coalesce(p_repair_high_cop,0)<0 then raise exception 'repair estimate cannot be negative'; end if;
  if p_repair_low_cop is not null and p_repair_base_cop is not null and p_repair_high_cop is not null and not(p_repair_low_cop<=p_repair_base_cop and p_repair_base_cop<=p_repair_high_cop) then raise exception 'repair estimates must satisfy low <= base <= high'; end if;
  if p_mark_reviewed then
    if exists(select 1 from unnest(v_values) v where v is null) then raise exception 'all risk dimensions are required'; end if;
    if p_repair_low_cop is null or p_repair_base_cop is null or p_repair_high_cop is null then raise exception 'all repair estimates are required'; end if;
  end if;
  select coalesce(max(case v when 'CRITICAL' then 4 when 'HIGH' then 3 when 'MEDIUM' then 2 when 'LOW' then 1 else 0 end),0) into v_score from unnest(v_values) v where v is not null;
  v_overall:=case v_score when 4 then 'CRITICAL' when 3 then 'HIGH' when 2 then 'MEDIUM' when 1 then 'LOW' else 'NOT_EVALUABLE' end;
  v_reviewed_at:=case when p_mark_reviewed then clock_timestamp() else null end;
  insert into public.lot_peritaje_reviews(lot_id,external_lot_id,source_attachment_url,mechanical_risk,transmission_risk,body_risk,safety_risk,electrical_risk,tires_risk,documentation_risk,missing_parts_risk,overall_risk,repair_low_cop,repair_base_cop,repair_high_cop,notes,reviewed_at,updated_at)
  values(v_lot_id,p_external_lot_id,p_source_attachment_url,v_values[1],v_values[2],v_values[3],v_values[4],v_values[5],v_values[6],v_values[7],v_values[8],v_overall,p_repair_low_cop,p_repair_base_cop,p_repair_high_cop,nullif(trim(coalesce(p_notes,'')),''),v_reviewed_at,clock_timestamp())
  on conflict(lot_id) do update set source_attachment_url=excluded.source_attachment_url,mechanical_risk=excluded.mechanical_risk,transmission_risk=excluded.transmission_risk,body_risk=excluded.body_risk,safety_risk=excluded.safety_risk,electrical_risk=excluded.electrical_risk,tires_risk=excluded.tires_risk,documentation_risk=excluded.documentation_risk,missing_parts_risk=excluded.missing_parts_risk,overall_risk=excluded.overall_risk,repair_low_cop=excluded.repair_low_cop,repair_base_cop=excluded.repair_base_cop,repair_high_cop=excluded.repair_high_cop,notes=excluded.notes,reviewed_at=excluded.reviewed_at,updated_at=clock_timestamp();
  insert into public.lot_peritaje_review_history(lot_id,external_lot_id,source_attachment_url,mechanical_risk,transmission_risk,body_risk,safety_risk,electrical_risk,tires_risk,documentation_risk,missing_parts_risk,overall_risk,repair_low_cop,repair_base_cop,repair_high_cop,notes,marked_reviewed)
  values(v_lot_id,p_external_lot_id,p_source_attachment_url,v_values[1],v_values[2],v_values[3],v_values[4],v_values[5],v_values[6],v_values[7],v_values[8],v_overall,p_repair_low_cop,p_repair_base_cop,p_repair_high_cop,nullif(trim(coalesce(p_notes,'')),''),p_mark_reviewed);
  return jsonb_build_object('ok',true,'external_lot_id',p_external_lot_id,'overall_risk',v_overall,'reviewed',p_mark_reviewed,'interpretation','MANUAL_PERITAJE_REVIEW_NOT_AUTOMATED_DIAGNOSIS');
end;$$;

revoke all on function public.dashboard_save_peritaje_review(text,text,text,text,text,text,text,text,text,text,numeric,numeric,numeric,text,boolean) from public,anon,authenticated;
grant execute on function public.dashboard_save_peritaje_review(text,text,text,text,text,text,text,text,text,text,numeric,numeric,numeric,text,boolean) to service_role;

create or replace view public.dashboard_peritaje_review_current as
select d.external_lot_id,d.lot_id,d.title,d.city,d.seller,d.current_bid_cop,d.closes_at,d.review_state,d.review_score,d.peritaje_count,d.peritajes,d.preliminary_headroom_before_fixed_costs_cop,
case when r.id is null then 'UNREVIEWED' when r.reviewed_at is null then 'DRAFT' else 'REVIEWED' end as peritaje_review_status,
r.source_attachment_url,r.mechanical_risk,r.transmission_risk,r.body_risk,r.safety_risk,r.electrical_risk,r.tires_risk,r.documentation_risk,r.missing_parts_risk,r.overall_risk,r.repair_low_cop,r.repair_base_cop,r.repair_high_cop,r.notes,r.reviewed_at,r.updated_at,
'MANUAL_PERITAJE_REVIEW_NOT_AUTOMATED_DIAGNOSIS'::text as interpretation
from public.dashboard_lot_current d left join public.lot_peritaje_reviews r using(lot_id) where d.peritaje_count>0;
revoke all on public.dashboard_peritaje_review_current from public,anon,authenticated;
grant select on public.dashboard_peritaje_review_current to service_role;